### ISSUE TITLE
Move VAT from Company to Payment?

### ISSUE THREAD

**Issue by krsriq** [FakerPHP/Faker#102]
Most localized providers that have a `vat` method have it in the Payment class (e.g. [es_ES](https://github.com/FakerPHP/Faker/blob/dd284b7e8c669ca5836debdd359f7eb1b747c543/src/Faker/Provider/es_ES/Payment.php#L32) or [fr_FR](https://github.com/FakerPHP/Faker/blob/dd284b7e8c669ca5836debdd359f7eb1b747c543/src/Faker/Provider/fr_FR/Payment.php#L20)) - except for two that have it in Company: [nl_NL](https://github.com/FakerPHP/Faker/blob/dd284b7e8c669ca5836debdd359f7eb1b747c543/src/Faker/Provider/nl_NL/Company.php#L101) and [zh_TW](https://github.com/FakerPHP/Faker/blob/dd284b7e8c669ca5836debdd359f7eb1b747c543/src/Faker/Provider/zh_TW/Company.php#L261).

Should we move the `vat` method of these two outliers to their respective Payment classes and call these methods from Company for BC? Should we then also mark them as deprecated in Payment?

**Comment by bramceulemans** [comment]
This is because (at least for the `nl_NL` locale), the logic of generating a VAT number is different for companies.

**Comment by pimjansen** [comment]
Difficult one. I think it belongs in company since it is a company government registration number.

It has nothing to do with payment only for tax reclaims. It is used in these flows though but not maintained
