### ISSUE TITLE
Move Russian Inn and Turkish TCNo from Calculator to localized providers

### ISSUE THREAD

**Issue by krsriq** [FakerPHP/Faker#106]
[`Calculator/Inn.php`](https://github.com/FakerPHP/Faker/blob/main/src/Faker/Calculator/Inn.php) verifies the Russian tax identification number (INN number), [`Calculator/TCNo.php`](https://github.com/FakerPHP/Faker/blob/main/src/Faker/Calculator/TCNo.php) the Turkish Identity Number - sounds like stuff that should be in localized providers?

Should we move the `Calculator/Inn.php` methods to `ru_RU/Company.php`, mark them deprecated in `Inn` and call the new methods in `Company.php` for BC? Similarly with `TCNo`/`tr_TR/Person.php`.

**Comment by bramceulemans** [comment]
From what I am reading (from a translated version of the Wikipedia article), the INN is both for legal entities and individuals, I don't think it should belong to `ru_RU/Company`.

Maybe it can go in `ru_RU/Payment`?

**Comment by krsriq** [comment]
> From what I am reading (from a translated version of the Wikipedia article), the INN is both for legal entities and individuals, I don't think it should belong to `Faker\Provider\ru_RU\Company`.
> 
> Maybe it can go in `Faker\Provider\ru_RU\Payment`?

It's already used in `Company` (and only there):
https://github.com/FakerPHP/Faker/blob/2e1bc4c64cdf8cb101cc416b4a660129af6029f5/src/Faker/Provider/ru_RU/Company.php#L99
...which doesn't mean that it wouldn't make more sense to have it in Payment though.

**Comment by pimjansen** [comment]
Agree with the proposal. We already flagged them at 2.0 that they are invalid so it's fine for me.

If INN is for both company as a person let's keep it in person maybe? I'm not from Russia so pretty hard to judge (the reason why the locales have to go)

**Comment by krsriq** [comment]
> From what I am reading (from a translated version of the Wikipedia article), the INN is both for legal entities and individuals, I don't think it should belong to `Faker\Provider\ru_RU\Company`.

Yes, but apparently there's a difference between the INN for individuals and companies: the first has 12 digits, the latter 10 (according for example to [this OECD document](https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/RussianFederation-TIN.pdf)). Our `ru_RU\Company::inn()` generates 10 digits and should therefore stay in `Company` IMO.

**Comment by bramceulemans** [comment]
I agree with you on the fact it should go in the Russian Company provider then, @krsriq. I think it should be renamed, though. Because if somehow a method personal INN is added too, it will overlap.

**Comment by krsriq** [comment]
Thanks @bramceulemans - renamed inn to inn10 now.
