### ISSUE TITLE
How about we enable single_quote in StyleCI?

### ISSUE THREAD

**Issue by krsriq** [FakerPHP/Faker#114]
String quotes are inconsistent (sometimes double, sometimes single). How about we enable [`single_quote`](https://docs.styleci.io/fixers#single_quote) in StyleCI to fix this?

_Originally posted by @krsriq in https://github.com/FakerPHP/Faker/pull/108#discussion_r537125858_

**Comment by bramceulemans** [comment]
I agree :')

I can also see where you got this from
