### ISSUE TITLE
Feature: Add Language name

### ISSUE THREAD

**Issue by kossa** [FakerPHP/Faker#132]
Hello,

The package support language Code using `languageCode ` but there is no language name like `English`, `Spanish`, `Arabic` ...

**Comment by pimjansen** [comment]
I think this is a nice addition but needs to be implemented in a lot of locales. But feel free to raise a PR for this next to the existing methods

**Comment by luchothoma** [comment]
I want to get the idea clear so I can help with a PR over this, It is to include 
```
// create a United States Englihs faker
$faker = Faker\Factory::create('en_US');
// with this can be done as
$faker = Faker\Factory::create('EnglishUnitedStates');

```
Or the other thing I can interprete is to resolve to an specific language code for a generic language specification

```
$faker = Faker\Factory::create('English');
// Will be always the same as 
$faker = Faker\Factory::create('en_US');
```

Which one of them(maybe neither) is the idea here ?

**Comment by pimjansen** [comment]
Both are wrong where the constructor is based on a locale.

I think what is meant is a method called languageName which should be implemented on the locales itself

**Comment by bramceulemans** [comment]
> I think what is meant is a method called languageName which should be implemented on the locales itself

This can not be done without breaking changes to existing code.

**Comment by pimjansen** [comment]
> > I think what is meant is a method called languageName which should be implemented on the locales itself
> 
> 
> 
> This can not be done without breaking changes to existing code.

We can safely add a new method to the class without breaking issue?

**Comment by bechir** [comment]
@pimjansen something like this:
```php
Faker\Factory::createFromName('English');
```

**Comment by pimjansen** [comment]
> @pimjansen something like this:
> 
> ```php
> 
> Faker\Factory::createFromName('English');
> 
> ```

Well i do not even see added benefit for this where Faker is fully locale based and not language based.

But this is totally not what the topic is about or am i wrong?

As far as i can see there is a request to output a localized language name and not only a code?

$faker->languageName; // French etc

Or am i missing something here?

**Comment by localheinz** [comment]
@kossa 

Can you clarify what feature you would like to see implemented? Can you provide an example?

**Comment by GrahamCampbell** [comment]
I dont think this is compatible with our plans for V2? // cc @Nyholm

**Comment by pimjansen** [comment]
> I dont think this is compatible with our plans for V2? // cc @Nyholm

Correct but r mean we cant adopt it in 2.x as well? Imo it would be a decent addition though

**Comment by Nyholm** [comment]
I don't see the benefit of adding this. We are moving away from using language/locales. So if this were to be added, we would deprecate it immediately. 

I vote a big 👎  for this feature. 

I would suggest we continue the work started in https://github.com/FakerPHP/Faker/pull/232 to move features to extensions as specified in https://github.com/Nyholm/next-faker/blob/master/PROVIDERS.md

**Comment by kossa** [comment]
> @kossa
> 
> Can you clarify what feature you would like to see implemented? Can you provide an example?

Let's say I have languages(id, name, is_default) table want to seed the name : English, Spanish, Arabic

**Comment by pimjansen** [comment]
@Nyholm but that can still mean we can include this in an interface somewhere

**Comment by Nyholm** [comment]
Could you elaborate?

**Comment by localheinz** [comment]
@kossa 

Are you looking for something like `$faker->languageName()`?

**Comment by localheinz** [comment]
@Nyholm 

There is nothing wrong with asking users requesting a feature what they are looking for.

On the other hand, https://github.com/FakerPHP/Faker/pull/244 was merged only a couple of days ago, adding a feature. 

I think we need to get everyone of the maintainers on the same page here.

**Comment by kossa** [comment]
> @kossa
> 
> Are you looking for something like `$faker->languageName()`?

Exactly

**Comment by pimjansen** [comment]
> Could you elaborate?

We will create interfaces for external locale extensions right?

Like a PersonInterface that will include a set of global methods to implement on all these extensions? Why cant we add Language Name on such interface to? I dont say we have to but its a valid usecase if you ask me
