### ISSUE TITLE
Replace imageUrl with the previous one or picsum

### ISSUE THREAD

**Issue by daison12006013** [FakerPHP/Faker#144]
I observed that we've changed our imageUrl from the Image provider, though it makes sence to provide a real image, what is the reason we replaced lorempixel into using placeholder.com?

Isn't it supposed to be make it as textImageUrl() instead?
TBH, text image isn't useful to foresee real life designs with expected image result.

```
<?php

namespace App\Faker;

use Faker\Provider\Image;

/**
 * Depends on image generation from https://picsum.photos
 */
class Picsum extends Image
{
    /**
     * {@InheritDoc}
     */
    public static function picsumUrl(
        $width = 640,
        $height = 480,
        $seed = null, // Tend to be the $category, but since picsum is randomized, we use it to cache instead
        $randomize = true,
        $word = null,
        $gray = false
    ) {
        $size     = "/$width/$height";
        $grayPath = $gray ? '?grayscale=1' : '';
        $seedPath = $seed !== null ? "/seed/$seed" : '';

        return strtr('https://picsum.photos{seed}{size}{gray}', [
            '{seed}' => $seedPath,
            '{size}' => $size,
            '{gray}' => $grayPath,
        ]);
    }
}
```

The above code is what I used now to override the Image provider, though this supposed to be the imageUrl() and replace the one we have to be textImageUrl().

**Comment by pimjansen** [comment]
The image provider will be removed from core in 2.x

We replaced it since the other service was down more then it was up which got a lot of complaints. Right now at least there is a working solution.

If you want something better please add a custom extension for now

**Comment by jenkoian** [comment]
I'm a big +1 on replacing placeholder.com with picsum (or maybe both?). Is there a roadmap or timeline for 2.x? I've skimmed through https://github.com/FakerPHP/Faker/discussions/15 and it doesn't sound close.

**Comment by pimjansen** [comment]
> I'm a big +1 on replacing placeholder.com with picsum (or maybe both?). Is there a roadmap or timeline for 2.x? I've skimmed through https://github.com/FakerPHP/Faker/discussions/15 and it doesn't sound close.

No there is no roadmap but feel free to add a custom provider. Future wise it will be removed so we are not putting effort in this
