### ISSUE TITLE
Doctrine\Common\Persistence vs Doctrine\Persistence

### ISSUE THREAD

**Issue by jnagels** [FakerPHP/Faker#149]
### Summary

Older versions of Doctrine use `Doctrine\Common\Persistence` while newer versions moved to `Doctrine\Persistence` as the namespace for classes like `ObjectManager`

In the original repository, there was already an open discussion (and MR) for this: https://github.com/fzaninotto/Faker/pull/2059
https://github.com/fzaninotto/Faker/issues/2055

I'm not 100% sure how long we should support both versions of Doctrine or how this backwards compatibility should be tackled. (Perhaps a major version upgrade? Or 2 separate Populators?)

**Comment by pimjansen** [comment]
The doctrine integration will be removed from core as of the next major.

We can add a check if the class exists to keep both and keep it backwards compatible as mentioned in the earlier pr?

**Comment by dpproject-pl** [comment]
Will it be moved to some external package or doctrine integration will be completely abandoned?

**Comment by pimjansen** [comment]
> Will it be moved to some external package or doctrine integration will be completely abandoned?

Will be removed from the core but a third party integration as an extension can be made by the community

**Comment by bramceulemans** [comment]
I suggest we make a v2 label to signal that something should be fixed in a future version.

**Comment by pimjansen** [comment]
> I suggest we make a v2 label to signal that something should be fixed in a future version.

Agree but this will be removed. I think we can still fix this in 1.x though since people will now have issues with certain doctrine versions

**Comment by pimjansen** [comment]
Since we do not have a valid scenario here, should we add a conflicts instead or leave it like this for now?

Problem of the conflicts is that we could also block people using never version of doctrine orm but now using this orm integration.

@GrahamCampbell what is your view?
