### ISSUE TITLE
Generates invalid US phone numbers

### ISSUE THREAD

**Issue by MatanYadaev** [FakerPHP/Faker#251]
### Summary

Faker is generating random invalid US phone numbers.
If you validate phone numbers in your app - you can't use Faker because of its randomness - sometimes it generates a valid phone number and tests pass, and sometimes it doesn't.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.0.0   |
| `fakerphp/faker`  | 1.13.0   |

### Self-enclosed code snippet for reproduction

```php
echo Faker\Factory::create('en_US')->phoneNumber; // 884.863.4355 - invalid
```

### Expected output

Faker should generate valid phone numbers.

### Actual output

Faker generates invalid phone numbers.

The PR that should fix this issue is still open: https://github.com/fzaninotto/Faker/pull/1838/files

**Comment by pimjansen** [comment]
Feel free to raise a similar PR here
