### ISSUE TITLE
Optional weight not working as intended

### ISSUE THREAD

**Issue by chinleung** [FakerPHP/Faker#271]
### Summary

In the documentation, it says that passing `1` to the `optional` modifier will always return the provider. However, when I pass 1, it's using the new percentage system, so there is actually only a 1% chance of returning the provider. Also, using the percentage based system, we will no longer be able to pass boolean values to the optional modifier.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.9   |
| `fakerphp/faker`  | 1.13.0   |

### Self-enclosed code snippet for reproduction

```php
app(Faker\Generator::class)->optional(1)->firstName;
```

### Expected output

```txt
John (Or any other first name)
```

### Actual output

```txt
null
```

**Comment by pimjansen** [comment]
As mentioned in the docs, if an int is provided it ranges from 0 to 100. So in your case 1/100 chance on the generator.

With a float it works from 0.00 to 1.00

**Comment by chinleung** [comment]
> As mentioned in the docs, if an int is provided it ranges from 0 to 100. So in your case 1/100 chance on the generator.
> 
> With a float it works from 0.00 to 1.00

@pimjansen Can you link me to where it says it in the doc please? I can't seem to find it. Maybe I'm not looking at the right place but in https://fakerphp.github.io/#modifiers, I don't see the mention of int and float.

```php
// optional() accepts a weight argument to specify the probability of receiving the default value.
// 0 will always return the default value; 1 will always return the provider. Default weight is 0.5 (50% chance).
$faker->optional($weight = 0.1)->randomDigit(); // 90% chance of NULL
$faker->optional($weight = 0.9)->randomDigit(); // 10% chance of NULL
```

**Comment by pimjansen** [comment]
Hmm its in the internal docblock. Can you confirm the suggestion works?

**Comment by chinleung** [comment]
> Hmm its in the internal docblock. Can you confirm the suggestion works?

Ah I see. It works passing a float.

**Comment by pimjansen** [comment]
Ok thanks! We will update the docs accordingly

**Comment by pimjansen** [comment]
https://github.com/FakerPHP/fakerphp.github.io/pull/39

**Comment by chinleung** [comment]
@pimjansen Sorry! I just tested this again and I think when I tested with the float, I didn't do `(float) 1`. When I pass a `(float) 1`, it's always returning the default provider.
