### ISSUE TITLE
Feature: Active URL

### ISSUE THREAD

**Issue by kw-pr** [FakerPHP/Faker#281]
### Summary

Some frameworks like Laravel support to validate [active urls](https://laravel.com/docs/8.x/validation#rule-active-url). It uses `dns_get_record` to check if A or AAAA dns record exists. 

It would be nice if faker had a function that provides only active urls.
Maybe freeEmailDomain could be used for a start.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.15   |
| `fakerphp/faker`  | 1.13.0   |

**Comment by pimjansen** [comment]
Dont think this should be in the Faker core though but could be supported from an extension in 2.0. It is a maintenance hell where domains keep changing

**Comment by bramceulemans** [comment]
Agreed with @pimjansen, closing.

/close
