### ISSUE TITLE
Release latest stuff

### ISSUE THREAD

**Issue by lukasjuhas** [FakerPHP/Faker#286]
Hello! First of all, thanks so much for the great package and for the great work!

I wanted to ask if it would be possible to make a release, I'm after some recent additions, more specifically #255 

Thanks!

**Comment by pimjansen** [comment]
Thanks! Will raise a release in a few days

**Comment by pimjansen** [comment]
See #288

**Comment by lukasjuhas** [comment]
Thank you @pimjansen !
