### ISSUE TITLE
Extract language into own packages

### ISSUE THREAD

**Issue by simonschaufi** [FakerPHP/Faker#287]
### Summary

As mentioned by François Zaninotto in his blog post about shutting down Faker, he wrotes that Faker is just too large because it includes data for 70+ languages. The goal would be to extract the language data into own repositories that can be included depending on the languages that you need for your tests/seeds.

**Comment by GrahamCampbell** [comment]
Yes, this is the plan. We have already got started with https://github.com/FakerPHP/Swedish. Hop on the slack for more discussion. :)
