### ISSUE TITLE
randomNumber return 0 every time

### ISSUE THREAD

**Issue by makbeth** [FakerPHP/Faker#290]
### Summary

Every time when I run the randomNumber() method, it returns a 0 value. I use it in Laravel 8.34.0 if it matters.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.0.1   |
| `fakerphp/faker`  | 1.14.0   |

### Self-enclosed code snippet for reproduction

```php
$faker = new \Faker\Generator();
$number = $faker->randomNumber();
echo $number; //0
```

### Expected output

```txt
every time a new random number
```

### Actual output

```txt
0
```

**Comment by pimjansen** [comment]
Confirmed that this is a bug

**Comment by pimjansen** [comment]
1.14.1 has just been pushed to resolve this issue.

Thanks!
