### ISSUE TITLE
randomHtml error

### ISSUE THREAD

**Issue by tanthammar** [FakerPHP/Faker#298]
### Summary

$this->faker->randomHtml(2,3)
Error:
```
PHP Deprecated:  Since fakerphp/faker 1.14: Accessing property "word" is deprecated, use "word()" instead. in /Users/tina/Sites/jetstream/vendor/symfony/deprecation-contracts/function.php on line 25
```

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8  |
| `fakerphp/faker`  | 1.14.1   |

### Self-enclosed code snippet for reproduction

```php
$this->faker->randomHtml(2,3)
```

**Comment by tanthammar** [comment]
If it matters. Laravel faker_locale is set to Swedish.

config/app.php
```php
    'faker_locale' => 'sv_SE',
```

**Comment by GrahamCampbell** [comment]
Deprecation warnings are not errors.

**Comment by pimjansen** [comment]
> Deprecation warnings are not errors.

Correct though a core method that invokes another core method should not invoke it though
