### ISSUE TITLE
curl 'via.placeholder.com/500' -> cloudflare 503 error

### ISSUE THREAD

**Issue by asolopovas** [FakerPHP/Faker#299]
### Summary

Hi there is problem with Image placeholders, which is not exactly the fault of the library but due to that $faker->image returns 0, it happens because when you curl via.placeholder.com/500 it will return 503 error. If you open link in the browser first time you get cloudflare ddos protection. Is there a way around it??

### Versions

1.14.1

**Comment by Okipa** [comment]
Same issue here. Seems that image generation would gain to be realized internally (a similar issue happened with lorempixel.com few month ago).

**Comment by pimjansen** [comment]
I see that the service is running fine again can you confirm?

We will not switch to internal generation where image generation will be removed to an extension since the next major release of Faker.

**Comment by Okipa** [comment]
Yes the service is running but is now protected under a Cloudflare DDOS attack protection (5 secs waiting then redirection) which seems to make it impossible to use with CURL.

Would you see any workaround to make it work ?

I think a lot of test suites are broken right now 😬

**Comment by pimjansen** [comment]
> Yes the service is running but is now protected under a Cloudflare DDOS attack protection (5 secs waiting then redirection) which seems to make it impossible to use with CURL.
> 
> Would you see any workaround to make it work ?
> 
> I think a lot of test suites are broken right now 😬

In that case we should create a separate extension for it to generate it via GD. But we do not want it in the core.

I will give it a go

**Comment by Okipa** [comment]
For information, Cloudflare protection has just been removed from https://placeholder.com.

But it seems to be a good move to handle this internally in a separate extension: base package would be lighter, it would provides more stability and would generate less avoidable HTTP requests.

**Comment by pimjansen** [comment]
Closed it since cloudflare protection has been removed and it works as expected now.

**Comment by Okipa** [comment]
Hi @pimjansen, the issue seems to be back => https://github.com/FakerPHP/Faker/issues/462

This is quite critical as it unfortunately blocks all test suites of projects based on generating false images for an unknown amount of time.

Are there any ongoing discussions about generating images directly from the package? It would be a much more reliable operation!
