### ISSUE TITLE
Invalid E.164 phone numbers

### ISSUE THREAD

**Issue by leon0399** [FakerPHP/Faker#300]
### Summary

E.164 phone numbers, generated by package seems to be invalid. 

For example, i've got generated `+6734232851178` and according to [google/libphonenumber](https://github.com/google/libphonenumber) it is invalid, here is an example: https://libphonenumber.appspot.com/phonenumberparser?number=%2B6734232851178

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.12   |
| `fakerphp/faker`  | 1.14.1   |

### Self-enclosed code snippet for reproduction

```php
$faker->valid()->e164PhoneNumber
```

### Expected output

Phone number to be valid

### Actual output

Phone number is invalid

**Comment by pimjansen** [comment]
https://en.wikipedia.org/wiki/Telephone_numbers_in_Brunei

So the Brunei needs 7 digits instead of 10 if im correct

**Comment by pimjansen** [comment]
Fix for this has been provided in our main branch. Will go with the next release.

Keep in mind that Faker is not implementing all logic so jnvalid numbers could occur. For now the format should be ok
