### ISSUE TITLE
PHP-Stan - Call to an undefined method.

### ISSUE THREAD

**Issue by laurentmuller** [FakerPHP/Faker#303]
### Summary

When running the PHP-Stan a warning is displayed:

`191    Call to an undefined method Faker\Generator::company(). `

### Versions

|                             | Version |
|:-------------------|:---------|
| PHP                     | 7.4.16   |
| Symfony              | 5.2.6     |
| `fakerphp/faker`  | 1.14.1   |

### Code snippet for reproduction

```php
$faker = Factory::create();
$company = $faker->company();
```

### Expected output
```txt
No Error.
```

### Actual output
```txt
191 Call to an undefined method Faker\Generator::company().
```

### Work around
```php
$faker = Factory::create();
$company = $faker->company;
```
But, in this case, a warning is logged:
```txt
Accessing property "company" is deprecated, use "company()" instead. 
```
This will be nice to update the Generator to propose the accessing method instead:
```php
...
@method string company()
@method string email()
...
class Generator
{
    // ....
}
```

**Comment by WengerK** [comment]
You got the same message with `safeEmail`.

```
$faker = Factory::create();
$faker->safeEmail;
```

Will generate a deprecation notice since 1.14

```
Accessing property "safeEmail" is deprecated, use "safeEmail()" instead. 
```

updating the code with

```
$faker = Factory::create();
$company = $faker->safeEmail();
```

Will throw `Call to an undefined method Faker\Generator::safeEmail().` on PHPStan & Psalm.

**Comment by GrahamCampbell** [comment]
This is a known problem, that will be addressed by re-architecting things to not be so magic. Discussed with @Nyholm and others.

**Comment by pimjansen** [comment]
I will close this issue, the properties en methods are added for next release so atleast those tools will not complain. Keep in mind that direct property access is deprecated and will be removed in future versions.
