### ISSUE TITLE
Please add the uuid() method to \Faker\Generator

### ISSUE THREAD

**Issue by drillcoder** [FakerPHP/Faker#304]
If you call the uuid() method on the Generator, then everything works because the Uuid provider exists and it has this method. But this method is not described in the Generator

**Comment by pimjansen** [comment]
Then why does it not work? Also please provide a valid bugreport

**Comment by drillcoder** [comment]
<img width="622" alt="Снимок экрана 2021-04-09 в 11 22 05" src="https://user-images.githubusercontent.com/20244032/114151525-de754880-9925-11eb-87d4-7c8bbdb7813a.png">
Everything works, but phpstorm and phpstan swear

**Comment by drillcoder** [comment]
We need to check the rest, found another languageCode

**Comment by pimjansen** [comment]
Duplicate of #303
