### ISSUE TITLE
Unknown formatter "catchPhrase"

### ISSUE THREAD

**Issue by laraluke** [FakerPHP/Faker#310]
### Summary

After updating to 1.14.1 `->catchPhrase` now throws the following error:

```
Unknown formatter "catchPhrase"
```

After brief investigations I believe it has been caused by the following commit affecting Laravel app's with `faker_locale` set to `en_GB`

https://github.com/FakerPHP/Faker/commit/7e6c6b0173a52e1a7c2c2f3428644b6ddb7b4089#diff-c65f89c9fc1f2402100a21efa32250b826e08a21c73aa1c84a6d023523132795

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.14   |
| `fakerphp/faker`  | 1.14.1   |

### Self-enclosed code snippet for reproduction

```php
$this->faker->catchPhrase
```

### Expected output

```txt
'Some catch phrase'
```

### Actual output

```txt
InvalidArgumentException 

Unknown formatter "catchPhrase"
```

**Comment by pimjansen** [comment]
As far as i know this has always been a locale specific method for en_US and never for the GB locale here.

So i do not really think it is a bug

**Comment by laraluke** [comment]
@pimjansen it has definitely been available to en_GB as I use it in most of my Laravel applications.

It was working before I updated to the latest version today.

**Comment by pimjansen** [comment]
The en_GB locale only has a new Company class since january 2021. Before this it did not even exist and that class never had a catchPhrase method. It only exists in the en_US locale.

Therefor i also do not see this as a bug.

**Comment by laraluke** [comment]
@pimjansen The commit I referenced did include the new en_GB Company class as you say, which is the problem. 

The class didn't exist before this commit which meant that the default fallback was the en_US Company class as shown here:

https://github.com/FakerPHP/Faker/blob/main/src/Faker/Factory.php#L7

So before the new en_GB Company class was created `->catchPhrase` worked as it fell back to en_US, but the newly created en_GB doesn't contain this method - causing the issue.

**Comment by laraluke** [comment]
I believe that `->catchPhrase` will be used in many other Laravel applications with the locale set to `en_GB` - so I propose that this method is moved into either the base Company class or added to the en_GB class too.

I'd be happy to submit a PR with either of the above solutions.

**Comment by pimjansen** [comment]
Feel free to raise a PR for this. Meaning implementing the catchPhrase methods on the en_GB provider if needed. Please note that we do not want linking between the locales itself.
