### ISSUE TITLE
Romania's phonenumber combinations gives random bad numbers that fail in validation

### ISSUE THREAD

**Issue by madalinignisca** [FakerPHP/Faker#321]
### Summary

Romania's phonenumber combination gives random validation on generated numbers.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.18   |
| `fakerphp/faker`  | 1.14.1   |

Preparing a patch with correct combinations.

Reference: https://github.com/google/libphonenumber/blob/7e9612a9112d498b61e5453538c4b0953969b46a/javascript/i18n/phonenumbers/metadatalite.js#L6212

**Comment by pimjansen** [comment]
We recently did a change on the main branch to fix the validation length on all numbers though. Is Romania that different?

**Comment by madalinignisca** [comment]
Almost all countries have strict combinations for telecom operators (and some allow portability, but it's another topic).

You can use this, which is an active maintained port of Google's library to validate phone numbers: https://github.com/giggsey/libphonenumber-for-php

It might help to provide real combinations for people that do not implement a 3rd party validation service, at least starting in the client.

Also, it won't affect people that do not validate numbers :)

PS: In Romania, also landlines have some additional rules, will dive into them later.

**Comment by pimjansen** [comment]
Yeah i know the lib. Will review the solution soon
