### ISSUE TITLE
Car faker

### ISSUE THREAD

**Issue by Velstad** [FakerPHP/Faker#331]
### Summary

I really need a generator of Types and Brands of cars.
I can't use "pelmered/fake-car" because it uses the new version of PHP ^ 7.3 || ^ 8.0
or the archived "fzaninotto/faker" package for my version of php.
Other unpopular packages are not updated. I need a package that will be regularly updated like this.

### Versions
php: ^7.2.5

|                | Version |
|:---------------|:--------|
| PHP            | 7.2.34   |
| `fakerphp/faker`  | 1.14.1   |

**Comment by bramceulemans** [comment]
You are free to make an extension, because until Faker 2.0 only fixes will be applied.

**Comment by IonBazan** [comment]
@Velstad I would suggest you to upgrade to PHP 7.3 or higher and continue using `pelmered/fake-car`. The latest version requires `fakerphp/faker`: https://github.com/pelmered/fake-car/releases/tag/1.6

**Comment by Velstad** [comment]
@bramceulemans  What do you mean?

**Comment by pimjansen** [comment]
> @bramceulemans  What do you mean?

There is no implementation for brands in the Faker core. If you want such thing, feel free to use the lib you mentioned are add your own custom extension for it.

**Comment by bramceulemans** [comment]
I recommend making a list of car brands and using our `randomElements()`

**Comment by Velstad** [comment]
My problem is solved: updating php to ^ 7.3.
