### ISSUE TITLE
Company name is not very random in some locales

### ISSUE THREAD

**Issue by cs278** [FakerPHP/Faker#333]
### Summary

The company name (`company()`) returns a small number of distinct results in some locales. The script below measures the distribution, the locales that are really problematic are probably these:

* bn_BD
* en_GB
* en_SG
* hy_AM
* ja_JP
* mn_MN
* th_TH

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | N/A   |
| `fakerphp/faker`  | `dev-main`   |

### Self-enclosed code snippet for reproduction

```php
<?php

use Composer\InstalledVersions;

require 'vendor/autoload.php';

$locales = array_map(fn($path) => basename($path), glob(InstalledVersions::getInstallPath('fakerphp/faker').'/src/Faker/Provider/*_*/'));

printf("%s\t%s\t%s\t%s\n", 'Locale', 'Max', 'Mean', 'Count');

foreach ($locales as $locale) {
    $faker = \Faker\Factory::create($locale);
    $names = [];

    for ($i = 0; $i < 10000; $i++) {
        $names[$faker->company()] = ($names[$faker->company()] ?? 0) + 1;
    }

    if (max($names) > 10) {
        printf("%s\t%u\t%.0f\t%u\n", $locale, max($names), round(array_sum($names) / count($names), 0), count($names));
    }
}
```

### Expected output

```txt
$ php -f test.php    | column -t
Locale  Max   Mean  Count
```

### Actual output

```
$ php -f test.php    | column -t
Locale  Max   Mean  Count
ar_JO   13    4     2853
ar_SA   18    5     1918
bn_BD   1127  1126  9
de_AT   11    3     3680
de_CH   17    3     3079
de_DE   12    2     4928
el_CY   13    2     4839
el_GR   25    13    812
en_GB   109   94    99
en_SG   1237  1233  8
en_ZA   29    19    493
fr_BE   14    4     2447
fr_CA   15    3     3395
fr_CH   15    3     3466
fr_FR   14    2     4537
hr_HR   13    4     2471
hu_HU   35    14    693
hy_AM   108   95    110
it_CH   15    3     3107
ja_JP   109   95    102
lt_LT   19    5     1943
me_ME   66    54    180
mn_MN   1159  1153  8
nl_BE   15    4     2445
pl_PL   12    3     3345
th_TH   117   106   92
uk_UA   38    23    450
zh_CN   47    32    324
zh_TW   11    3     3720
```

**Comment by pimjansen** [comment]
Most of these locales have no specific implementation there.

Feel free to propose updates when we split these as extensions for 2.x

**Comment by IonBazan** [comment]
I think we should load `en_US` by default and then allow developers to overload some of the generators by desired locale. This should either happen automatically or be better documented as I feel developers expect any missing provider in their locale to return a random value in English locale (as fallback).

**Comment by cs278** [comment]
Why is this marked wont fix? Will you not accept a PR against 1.x to make improvements? Currently we cannot reliably use the `en_GB` locale with `unique()` and it's not the worst one on this list.

**Comment by pimjansen** [comment]
Indeed, 1.x is closed for enhancements, see contribution guide

**Comment by cs278** [comment]
> At the moment we are not looking for pull requests that add new features.

I'm not suggesting any new features just fixing the existing code so it's usable.
