### ISSUE TITLE
Feature Request: "version" generator

### ISSUE THREAD

**Issue by aedart** [FakerPHP/Faker#335]
It would be really great if Faker could offer a `version` generator, able to return a valid version string, acc. to [Semantic Versioning](https://semver.org/).

### Example:
```php
echo $faker->version; // 2.11.3
```

This should be a relative small addition that could perhaps become part of current (or version 2.x) of Faker.

**Nb**: _I'm sorry if this feature request is misplaced. I was sadly not able to find any valid information about where such should be created / placed._

**Comment by IonBazan** [comment]
While this could be a nice addition, you can use `numerify('#.##.#')` for now.

**Comment by pimjansen** [comment]
Well its a decent addition imo for the future. I would not call it version though since there are so many versioning types but we could create such extension indeed.

Like:
$faker->semver(); // 1.0.0
$faker->semver(); // 2.1.7-beta1
$faker->version(); // random options like semver or even other formats

**Comment by aedart** [comment]
@IonBazan Thank for the reply - I'm in no rush for this feature. I only brought it up, due to a recent testing task I had to complete, in which a version string was required.

@pimjansen I agree that "version" alone might be a bit too shallow. A version generator could... or rather should, allow for some level of customization. Which options should be allowed is beyond me, at this very moment. In any case, I hope that this can be adapted into a future version of Faker.

**Comment by shalvah** [comment]
Whoa, slow down, bot. 14 days is a bit aggressive for a "stale" tag for a (non-urgent) feature request.😕

**Comment by pimjansen** [comment]
> Whoa, slow down, bot. 14 days is a bit aggressive for a "stale" tag for a (non-urgent) feature request.

Thats why we have a pinned label :)

**Comment by chris-doehring** [comment]
I really like the idea and was actually wondering why Faker doesn't already have something like that^^ I tried a `semver` implementation in #350 :)

**Comment by chris-doehring** [comment]
Another versioning scheme I've found is [`CalVer`](https://calver.org/), the calendar based versioning, but that's pretty much it. Many applications or companies define their own versioning scheme, but semver and calver seem to be the biggest ones available.

After implementing that, we can add the `version` method which will randomly generate one of those two schemes, like @pimjansen suggested.

**Comment by pimjansen** [comment]
Im closing this ticket. If we need more support for other versions and would do it from there though.

Thanks for the effort!
