### ISSUE TITLE
Company nl_NL locale using a deprecated property accessor

### ISSUE THREAD

**Issue by denzity86** [FakerPHP/Faker#344]
https://github.com/FakerPHP/Faker/blob/89c6201c74db25fa759ff16e78a4d8f32547770e/src/Faker/Provider/nl_NL/Company.php#L87

The `lastName` property should be replaced with `lastName()` instead

**Comment by pimjansen** [comment]
Thanks this is indeed invalid

**Comment by pimjansen** [comment]
@bramceulemans can you have a look at the linked PR?
