### ISSUE TITLE
Faker->state not available anymore

### ISSUE THREAD

**Issue by JBx0** [FakerPHP/Faker#346]
### Summary

The new version seems to be handling that specific call ($faker->state)differently ? Or simply removed it ? 

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | ^8.0   |
| `fakerphp/faker`  | 1.15   |

### Self-enclosed code snippet for reproduction

```php
$this->faker = Factory::create('de_DE');
$this->faker->state
```

### Expected output

```txt
Any state (Using german local)
```

### Actual output

```txt
 Access to an undefined property Faker\Generator::$state.
 ```

works on 1.14.1

**Comment by pimjansen** [comment]
Did you try state() instead?

**Comment by JBx0** [comment]
sure thing, same result

**Comment by pimjansen** [comment]
Unable to reproduce this issue on `v1.15.0`

```
root@af6d37109d98:/app# php -v
PHP 8.0.8 (cli) (built: Jul  1 2021 22:40:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
root@af6d37109d98:/app# php test.php 
Hessen
```

```php
<?php

require './vendor/autoload.php';

$faker = \Faker\Factory::create('de_DE');
echo $faker->state().PHP_EOL;
```

**Comment by JBx0** [comment]
`•100% ➜ php -v
Xdebug: [Config] The setting 'xdebug.remote_enable' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
PHP 8.0.7 (cli) (built: Jun  4 2021 03:56:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.7, Copyright (c) Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.7, Copyright (c), by Zend Technologies`
    
surprisingly It is there but neither my IDE nor phpstan nor executing the code can find it + it is only the "state"
I'm confused ^^
Did you guys change something in the generator?

Symfony 4.4 
FakerPHP 1.15.0
![Screenshot 2021-07-08 at 21 46 13](https://user-images.githubusercontent.com/75067185/124981555-fe57fd80-e035-11eb-8cab-51ccc7b6de32.png)


🤔 
    
![Screenshot 2021-07-08 at 21 39 36](https://user-images.githubusercontent.com/75067185/124981167-8ab5f080-e035-11eb-8ced-f44114701739.png)
![Screenshot 2021-07-08 at 21 42 29](https://user-images.githubusercontent.com/75067185/124981169-8ab5f080-e035-11eb-88b9-1e9e08b8f104.png)
![Screenshot 2021-07-08 at 21 40 40](https://user-images.githubusercontent.com/75067185/124981170-8b4e8700-e035-11eb-87a1-bd9f4b31e276.png)
![Screenshot 2021-07-08 at 21 39 47](https://user-images.githubusercontent.com/75067185/124981172-8b4e8700-e035-11eb-84a2-5c8abdd2f1ec.png)

**Comment by pimjansen** [comment]
This is correct since it is a specific implementation for the German locale.

Since all the loading is done magically there is no direct reference thus your IDE will never know it.

It is something that is on our radar while rebuilding Faker 2.c though

**Comment by JBx0** [comment]
What changed from version 14.1 to 15.0 cause in 14.1 it works with everything. We are most likely downgrading back to 14.1

**Comment by pimjansen** [comment]
Nothing it was also not there in 1.14.1 (just verified).
