### ISSUE TITLE
Incorrect static analysis types (all union types missing)

### ISSUE THREAD

**Issue by shalvah** [FakerPHP/Faker#349]
It seems like #307 incorrectly updated the types for union types. See https://github.com/FakerPHP/Faker/issues/307#issuecomment-878172742.

For example, `->shuffle()` still returns an array or string, but the docblock type is incorrectly set to only `array`, throwing false positives in static analysis.

It looks like all generators with union types like `shuffle`, `words`, `randomKey`, etc were wrongly set to only the first type. (I'm guessing maybe a find + replace regex that did not go well.🤔)

**Comment by pimjansen** [comment]
I do not see this changed in that PR? Can you also please provide a code snippet and so on as defined in the template

**Comment by shalvah** [comment]
Here's [the direct link to the file](https://github.com/FakerPHP/Faker/pull/307/files?file-filters%5B%5D=.php#diff-31471b0b25bb74ef183af00be15790b9e3f2c1488a29d7c1f113ef794281c6a3).

The diff is collapsed by default because it's a large file. You need to click on "Load diff". 


Alternatively, you can see the difference by comparing: here's `shuffle` in the [current version](https://github.com/FakerPHP/Faker/blob/main/src/Faker/Generator.php#L87) vs what was there [before #307 was merged](https://github.com/FakerPHP/Faker/blob/ffb273bb6b9553a4c5471af504d3493ac49c1712/src/Faker/Generator.php#L172).

I'm not sure the reason for the change, tbh, because the static types worked just fine for me in the past, but I'm guessing you probably know of some other use case where they didn't.

**Comment by shalvah** [comment]
I've opened a PR with the fix #352 .
