### ISSUE TITLE
state and secondaryAddress phpdoc

### ISSUE THREAD

**Issue by lugosium** [FakerPHP/Faker#356]
### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.0.0   |
| `fakerphp/faker`  | 1.15.0   |

### Self-enclosed code snippet for reproduction

```php
$this->faker->secondaryAddress
$this->faker->state
```

### Expected output

```txt
No errors in PHPStan
```

### Actual output

```txt
Access to an undefined property Faker\Generator::$secondaryAddress.
Access to an undefined property Faker\Generator::$state.
```

From #307, will do PR later.

**Comment by GrahamCampbell** [comment]
Calling properties is deprecated in favour of method calls. New functionality will not be implemented with support for properties.

**Comment by lugosium** [comment]
Thanks for your quick feedback.

Ok, so the mr needs to be something like:

```
@property string $secondaryAddress 
@method string secondaryAddress()

@property string $state 
@method string state()
```

And in my code

```
$this->faker->secondaryAddress()
$this->faker->state()
```

If i understood correctly?

**Comment by pimjansen** [comment]
For which locale is this?

**Comment by lugus** [comment]
It is for default locale, 'en_US'.

Issue is from v1.1.15

**Comment by pimjansen** [comment]
@GrahamCampbell i think the main issue here is that the methods are not generic but locale specific. Therefor they are did not have a typehint in phpdoc.

This is an overall design flaw in the original Faker setup. Defining them will give you drawbacks the other way around

**Comment by lugosium** [comment]
As it was working before v1.15, can't we just re-add these lines for now?

https://github.com/FakerPHP/Faker/pull/307/files#diff-31471b0b25bb74ef183af00be15790b9e3f2c1488a29d7c1f113ef794281c6a3L32

https://github.com/FakerPHP/Faker/pull/307/files#diff-31471b0b25bb74ef183af00be15790b9e3f2c1488a29d7c1f113ef794281c6a3L35

**Comment by pimjansen** [comment]
Well the things is that we will push locale specific things in the generator which is a bit odd imo.

@GrahamCampbell you got an idea on this?

**Comment by pimjansen** [comment]
We discussed this and this will not be re-added since it is locale specific. It will only add noise for all other locales where it does not exists.

For faker 2.x will have taken this into account and bo magic methods will remain
