### ISSUE TITLE
UniqueGenerator is missing PHPDocs with available methods

### ISSUE THREAD

**Issue by Kolyunya** [FakerPHP/Faker#361]
### Summary

`UniqueGenerator` is missing PHPDocs with available methods. This makes it impossible to perform static analysis of the code like this:

```php
$faker->unique()->url();
```

Code like this yields errors like:

```
Call to an undefined method Faker\UniqueGenerator::url().
```

There are couple of ways to fix this:
* Copy and paste PHPDocs with methods from `Generator`. This obviously violates the DRY principle.
* Extend `UniqueGenerator` from the `Generator`. Can potentially flaw the library architecture.
* Create a trait with nothing more than PHPDocs and use it in all generators. This is the least invasive option IMO.

I can make a PR for that if we decide which strategy to stick to.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | any   |
| `fakerphp/faker`  | 1.15.0   |

**Comment by bramceulemans** [comment]
I agree with making a generator interface or trait

**Comment by Kolyunya** [comment]
@bramceulemans the problem with the `interface` is that we wouldn't be able to implement it since all the methods are magic.

**Comment by i-bajrai** [comment]
Needs the doc block as per the generator class

You can force the type to be of the `vendor/fakerphp/faker/src/Faker/Generator.php` class

```
/** @var Generator $unique */
$unique = $this->faker->unique();
```

```
/**
 * Proxy for other generators, to return only unique values. Works with
 * Faker\Generator\Base->unique()
 *
 * @property string $citySuffix
 *
 * @method string citySuffix()
 *
 * @property string $streetSuffix
 *
 * @method string streetSuffix()
 *
 ......
 *
 * @property string $uuid
 *
 * @method string uuid()
 */
 ```

**Comment by Kolyunya** [comment]
The problem was caused by the fact that I was using the older version of the library. Currently, generators have the `@mixin Generator` annotation.
