### ISSUE TITLE
Typo in regex that matches (e.g.) "Faker\Core\Class->method"

### ISSUE THREAD

**Issue by jmorganmartin** [FakerPHP/Faker#363]
It looked like there was a typo in the regex on this line:

https://github.com/FakerPHP/Faker/blob/3647f54490175f210e6246d1ee0a19c186757cf7/src/Faker/Generator.php#L643

The regex currently used there:
```
^([a-zA-Z0-9\\\]+)->([a-zA-Z0-9]+)$
```
Matches the intended pattern `Faker\Core\Barcode->ean13`, but it's a bit confusing why `\\\` works in that case. It's very PHP-specific stuff with PHP and backslashes in strings/regexes. Best I can tell, the third backslash is only required (and only works*) because the backslashes immediately proceed a `]`, which itself _can_ be escaped by a backslash. 

While the current regex works in PHP, according to _generic_ regex rules, it is too aggressive as far as what it will match: https://regex101.com/r/TdDNJu/1

I believe this satisfies the requirement a little more clearly/universally:

```
^([\\a-zA-Z0-9]+)->([a-zA-Z0-9]+)$
```

You can see that it matches here: https://regex101.com/r/sWLbhL/1

Alternately, 4 slashes also work both in PHP (no matter where they are located within the capture group) and as defined in generic regex specs:

```
^([a-zA-Z0-9\\\\]+)->([a-zA-Z0-9]+)$
```
or
```
^([\\\\a-zA-Z0-9]+)->([a-zA-Z0-9]+)$
```

\* Note: if 3 backslashes were used at the _beginning_ of the group: `^([\\\a-zA-Z0-9]+)->([a-zA-Z0-9]+)$`, it actually changes the capturing group slightly: https://regex101.com/r/l9YfeM/1

**Comment by pimjansen** [comment]
Can you test this out and raise a PR for this?
