### ISSUE TITLE
semver method missing

### ISSUE THREAD

**Issue by allastore** [FakerPHP/Faker#364]
### Summary

According to the documentation present at the link
https://fakerphp.github.io/formatters/version/ I should be able to get a semantic version instead I get an error 

### Versions

composer info fakerphp/faker

name     : fakerphp/faker
descrip. : Faker is a PHP library that generates fake data for you.
keywords : data, faker, fixtures
versions : * v1.15.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/FakerPHP/Faker.git 89c6201c74db25fa759ff16e78a4d8f32547770e
dist     : [zip] https://api.github.com/repos/FakerPHP/Faker/zipball/89c6201c74db25fa759ff16e78a4d8f32547770e 89c6201c74db25fa759ff16e78a4d8f32547770e
path     : vendor/fakerphp/faker
names    : fakerphp/faker

support
issues : https://github.com/FakerPHP/Faker/issues
source : https://github.com/FakerPHP/Faker/tree/v1.15.0

autoload
psr-4
Faker\ => src/Faker/

requires
php ^7.1 || ^8.0
psr/container ^1.0
symfony/deprecation-contracts ^2.2

requires (dev)
bamarni/composer-bin-plugin ^1.4.1
ext-intl *
symfony/phpunit-bridge ^4.4 || ^5.2

suggests
ext-curl Required by Faker\Provider\Image to download images.
ext-dom Required by Faker\Provider\HtmlLorem for generating random HTML.
ext-iconv Required by Faker\Provider\ru_RU\Text::realText() for generating real Russian text.
ext-mbstring Required for multibyte Unicode string functionality.

conflicts
fzaninotto/faker *

Test with PHP 7.2.15 & 7.4.22

### Self-enclosed code snippet for reproduction

```php
<?php
require_once 'vendor/autoload.php';

$faker = Faker\Factory::create();

echo $faker->semver();
```
### Expected output

```txt
 A semantic version string like
0.0.1
```

### Actual output

```txt

PHP Fatal error:  Uncaught InvalidArgumentException: Unknown formatter "semver" in vendor/fakerphp/faker/src/Faker/Generator.php:644
Stack trace:
#0 vendor/fakerphp/faker/src/Faker/Generator.php(622): Faker\Generator->getFormatter('semver')
#1 vendor/fakerphp/faker/src/Faker/Generator.php(850): Faker\Generator->format('semver', Array)
#2 faker.test.php(6): Faker\Generator->__call('semver', Array)
#3 {main}
  thrown in vendor/fakerphp/faker/src/Faker/Generator.php on line 644

```

**Comment by pimjansen** [comment]
Correct, it is not released yet. Will be there in the next minor

**Comment by allastore** [comment]
![immagine](https://user-images.githubusercontent.com/11774957/129879414-0e7e17e9-64be-41cb-b535-5bdb05921cdb.png)

OK it's not a big problem but it would be possible to mark the functionality as "to-be" or "future" because in the documentation at the top right is reported version 1.5.0 and it seems to me that this may be confusing or not intuitive.
Thanks.

**Comment by pimjansen** [comment]
Correct, will release it end of this week to make it just as easy

**Comment by tylerwiegand** [comment]
lol i just went crazy for 15 minutes wondering why this wasn't registering, trying to add providers...smh... glad i found this!
