### ISSUE TITLE
When will v1.16 be released?

### ISSUE THREAD

**Issue by spawnia** [FakerPHP/Faker#365]
Hi, thank you to the maintainers for keeping this project up and running.

It has been 1 month since my pull request (#345) was merged. I am now wondering when a new release will be made. Is there anything stopping a release of what is currently in `main`?

Given this library has a comprehensive test suite, I would tend to think that every successful merge to `main` could be released as soon as it hits. In my own projects, I have had a pretty good experience with releasing early, often, and in small increments; given the proper automation is in place. Is that something I could help with? Happy to remove potential blockers and allow this project to move more quickly.

**Comment by spawnia** [comment]
Thanks stalebot, nothing happening is the reason for this issue.

**Comment by pimjansen** [comment]
Will release it soon. We are still waiting for another issue to clear

**Comment by chris-doehring** [comment]
[v1.16.0](https://github.com/FakerPHP/Faker/releases/tag/v1.16.0) has just been released.
