### ISSUE TITLE
catchPhrase method is not declared.

### ISSUE THREAD

**Issue by laurentmuller** [FakerPHP/Faker#387]
### Summary

In the [Faker\Provider\en_US\Company](https://fakerphp.github.io/formatters/#fakerprovideren_uscompany) class, the `catchPhrase()` method is defined; but not in the `Faker\Generator` class.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.24   |
| `fakerphp/faker`  | 1.16.0   |

### Expected output

Add the method to the Generator.

```php
@method string catchPhrase()
```

**Comment by pimjansen** [comment]
This is a locale specific method and therefor not in the generator
