### ISSUE TITLE
Localize the month names and day names.

### ISSUE THREAD

**Issue by laurentmuller** [FakerPHP/Faker#388]
### Summary

The [monthName](https://fakerphp.github.io/formatters/date-and-time/#monthname) and the [dayOfWeek](https://fakerphp.github.io/formatters/date-and-time/#dayofweek) are always returned with English format. 
In general, all dates are formatted in English

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.24   |
| `fakerphp/faker`  | 1.16.0   |

### Self-enclosed code snippet for reproduction

```php
echo $faker->monthName();  // 'December'
echo $faker->dayOfWeek(); // 'Tuesday'
```

### Expected output

Say that locale used with the Generator is set to `fr_FR`:

```php
echo $faker->monthName();  // 'Décembre'
echo $faker->dayOfWeek(); // 'Mardi'
```
One way to solve this problem is to use the locale from the Generator class to format the dates.

```php
setlocale(LC_TIME, 'fr_FR');
```

**Comment by pimjansen** [comment]
Its up to a locale implementation to extend this

@bram-pkg this is correct right?

**Comment by bram-pkg** [comment]
Yes, if a provider does not include those methods, the en_US provider will be used as fallback.

**Comment by laurentmuller** [comment]
I more or less agree with you. When creating the Generator, the locale parameter is provided. 

It could be used to format the dates.

**Comment by pimjansen** [comment]
> I more or less agree with you. When creating the Generator, the locale parameter is provided. 
> 
> 
> 
> It could be used to format the dates.  

Correct but the provider has not implemented those methods so they are used from core which in this case falls back on english. Feel free to implement the methods for the locale
