### ISSUE TITLE
faker image return false

### ISSUE THREAD

**Issue by Temepest74** [FakerPHP/Faker#389]
### Summary

When I run this command from cmd I get the output false

```
PS D:\Applications\Programming\WAMP\www> php artisan tinker
Psy Shell v0.10.9 (PHP 7.4.9 — cli) by Justin Hileman
>>> \Faker\Factory::create()->image(storage_path('app/public/folder'))                                                                                                                                         
=> false
```

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.9   |
| `fakerphp/faker`  | 1.16.1   |
| Windows | 11 |

I was hoping it was a permission problem, but running cmd as administrator makes no difference

**Comment by pimjansen** [comment]
It fails silent here what is intended when not all prerequisites are met. Is curl enabled in your php installation?
