### ISSUE TITLE
Suggest installing this package when indicating fzaninotto/faker is abandoned

### ISSUE THREAD

**Issue by bkuhl** [FakerPHP/Faker#40]
Updating composer dependencies currently leads to:

`Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.`

It'd be great if this package was suggested instead.

**Comment by pimjansen** [comment]
Agreed however this needs to be set at the original repository and not here.

**Comment by bkuhl** [comment]
Yeah, but I figured a tweet from Taylor or something might be what it would take to make that happen. Me posting an issue on that repo is unlikely to make it happen.

**Comment by GrahamCampbell** [comment]
Yes, please contact the upstream author directly. :)
