### ISSUE TITLE
"FakerPHP" Name

### ISSUE THREAD

**Issue by joseph-levine** [FakerPHP/Faker#404]
The PHP Group asks that "PHP" not be used in project names. (https://www.php.net/license/index.php)

This is a great project, and it should respect the language. Let's not turn into Python.

**Comment by bram-pkg** [comment]
The text in question:

```
Q. I've written a project in PHP that I'm going to release as open source, and I'd like to call it PHPTransmogrifier. Is that OK?

A. We cannot really stop you from using PHP in the name of your project unless you include any code from the PHP distribution, in which case you would be violating the license. See Clause 4 in the PHP License v3.01.
But we would really prefer if people would come up with their own names independent of the PHP name.

"Why?" you ask. You are only trying to contribute to the PHP community. That may be true, but by using the PHP name you are explicitly linking your efforts to those of the entire PHP development community and the years of work that has gone into the PHP project. Every time a flaw is found in one of the thousands of applications out there that call themselves "PHP-Something" the negative karma that generates reflects unfairly on the entire PHP project. We had nothing to do with PHP-Nuke, for example, and every bugtraq posting on that says "PHP" in it. Your particular project may in fact be the greatest thing ever, but we have to be consistent in how we handle these requests and we honestly have no way of knowing whether your project is actually the greatest thing ever.

So, please, pick a name that stands on its own merits. If your stuff is good, it will not take long to establish a reputation for yourselves. Look at Zope, for example, that is a framework for Python that doesn't have Python in the name. Smarty as well doesn't have PHP in the name and does quite well.
```

**Comment by bram-pkg** [comment]
@GrahamCampbell @pimjansen I think this is a good point, renaming the package in Packagist would however cause a quite big annoyance for end users.

**Comment by pimjansen** [comment]
Little too late though. It will be a gigantic mess i think to update again

**Comment by bram-pkg** [comment]
I think renaming the organization on GitHub should be possible, but finding an alternative name will be hard.

**Comment by pimjansen** [comment]
> I think renaming the organization on GitHub should be possible, but finding an alternative name will be hard.

All is possible but it will also mean that all projects should update deps. Imo that is really not a good thing.

In that case i'd rather write something about this in our policies and such

**Comment by GrahamCampbell** [comment]
I don't know the history of how the PHP team decided they wanted to post that FAQ, however this FAQ seems in contradiction with how the community currency functions. Very many packages include the name PHP, including PHPUnit and PHPStan. I am not going through a rename for no benefit.

**Comment by bram-pkg** [comment]
Agreed, @GrahamCampbell.
