### ISSUE TITLE
Faker/ORM/Doctrine not working with latest doctrine implementations

### ISSUE THREAD

**Issue by icanhazstring** [FakerPHP/Faker#413]
### Summary
The current version of faker uses the following classes of Doctrine

- `Doctrine\Common\Persistence\ObjectManager`
- `Doctrine\Common\Persistence\Mapping\ClassMetadata`

As seen here:
https://github.com/FakerPHP/Faker/tree/main/src/Faker/ORM/Doctrine

`doctrine/persistence` with version `1.3` moved the classes around.
With version `2.0` these aliases were gone, this is when faker will stop working.

We have two options here:
1. Release a fix adding a simple alias (same as doctrine/persistence https://github.com/doctrine/persistence/blob/1.3.x/lib/Doctrine/Common/Persistence/ObjectManager.php)
2. Add a `conflict` in `composer.json` to avoid installing with doctrine/persistence below ^2.0 and use the new classes.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.x   |
| `fakerphp/faker`  | latest   |

### Current quickfix
To quickly work around this issue I added these two lines into my `tests/bootstrap.php`

```
class_alias(\Doctrine\Persistence\ObjectManager::class, 'Doctrine\Common\Persistence\ObjectManager');
class_alias(\Doctrine\ORM\Mapping\ClassMetadata::class, 'Doctrine\Common\Persistence\Mapping\ClassMetadata');
```

**Comment by fdiedler** [comment]
Hi,

Have the same problem using Faker in Fixtures (Symfony 5.4) 

```
public function load(ObjectManager $manager): void {
     $faker = Factory::create("fr_FR");
     $populator = new \Faker\ORM\Doctrine\Populator($faker, $manager);
     $populator->addEntity('Market', 5);
     $insertedPKs = $populator->execute();
}
```

The error is : 

> Faker\ORM\Doctrine\Populator::__construct(): Argument #2 ($manager) must be of type ?Doctrine\Common\Persistence\ObjectManager, Doctrine\ORM\EntityManager given, called in C:\Users\florent\Desktop\wehost\o
  ctopus-v2\src\DataFixtures\AppFixtures.php on line 33

Do you plan to fix it ? 

Thanks,

**Comment by icanhazstring** [comment]
> Hi,
> 
> Have the same problem using Faker in Fixtures (Symfony 5.4) 
> 
> ```
> public function load(ObjectManager $manager): void {
>      $faker = Factory::create("fr_FR");
>      $populator = new \Faker\ORM\Doctrine\Populator($faker, $manager);
>      $populator->addEntity('Market', 5);
>      $insertedPKs = $populator->execute();
> }
> ```
> 
> The error is : 
> 
> > Faker\ORM\Doctrine\Populator::__construct(): Argument #2 ($manager) must be of type ?Doctrine\Common\Persistence\ObjectManager, Doctrine\ORM\EntityManager given, called in C:\Users\florent\Desktop\wehost\o
>   ctopus-v2\src\DataFixtures\AppFixtures.php on line 33
> 
> Do you plan to fix it ? 
> 
> Thanks,
> 

This should be fixed as well.
For the time being the `class_alias` should also work as a quick fix.

**Comment by fdiedler** [comment]
Thanks for the quick workaround, it works :)
