### ISSUE TITLE
Add a `not` modifier

### ISSUE THREAD

**Issue by marc-mabe** [FakerPHP/Faker#420]
This would be a shortcut for `valid` where the argument should not match the given value.

like `$faker->not('NL')->countryCode()` or chaining to disallow multiple values `$faker->not('NL')->not('DE')->countryCode()`.

In my case this would be much shorter and more readable than:
```php
$newCountryCode = $faker->valid(fn ($countryCode) => $countryCode !== $station['countryCode'])->countryCode();
$I->sendPATCH('/v1/station/' . $station['id'], ['countryCode' => $newCountryCode]);
```

PS: `unique` does not work well here as I need to generate more country codes then exists and in case like the above I only care about getting one not equal to specific one.

**Comment by bram-pkg** [comment]
Hi, while we might consider adding this, I have a suggestion for you.

It would be easier to use `in_array` in your use case.

Example:

```php
$countryCode = $faker->valid(fn ($code) => ! in_array($code, ['NL', 'BE']))
                     ->countryCode()
```

**Comment by marc-mabe** [comment]
Hi @bram-pkg,
