### ISSUE TITLE
Slash is not ignored in regexify() in some cases

### ISSUE THREAD

**Issue by vipankumar87** [FakerPHP/Faker#425]
### Versions

|                | Version |
|:---------------|:--------|
| PHP            | x.y.z   |
| `fakerphp/faker`  | x.y.z   |

### Self-enclosed code snippet for reproduction

```php
# replace this with a self-enclosed usage example
```

### Expected output

```txt
# replace this with the expected output of your self-enclosed example
```

### Actual output

```txt
# replace this with the actual output of your self-enclosed example
```

**Comment by bram-pkg** [comment]
Hi, could you leave an example in the designated fields?
