### ISSUE TITLE
Faker container builder cant reach extension locally

### ISSUE THREAD

**Issue by pimjansen** [FakerPHP/Faker#426]
Hey guys,

I have been diving in our current setup on the `Extensions` while building the Dutch language extension with Bram. We noticed that technically all is working fine however there is no reference to the Generator while calling methods directly.

```php
$faker = Faker\Dutch\Factory::netherlands();
$faker->ext(MyClass\Extension)->myMethod(); // Will work
$faker->myMethod(); // Will not work
```

The problem with this is for the fact that the Generator itself is not aware of the extensions and therefor the method can not be reached directly. If i will review this on usability it would be something we would like i guess? Calling the extension every time is messy espacially when you mix methods from `core` and an actual extension that is registered by the container builder.

To fix this it is quite easy, make the generator aware of the extensions. It actually already is in the container itself however the ContainerInterface does not let us iterate through the extensions that are registered meaning we cant reach them.

Let me know you thoughts

Best,
Pim

**Comment by pimjansen** [comment]
@bram-pkg the issue we discussed earlier

**Comment by bram-pkg** [comment]
I'm going to do some thing about how to resolve this.

Most of my solutions right now involve somehow extending the psr/container to include a all() function, to retrieve a list of all contained definitons.

**Comment by pimjansen** [comment]
> I'm going to do some thing about how to resolve this.
> 
> 
> 
> Most of my solutions right now involve somehow extending the psr/container to include a all() function, to retrieve a list of all contained definitons.

Yeah indeed and we have decided if this is something we want though. If we do so it is pretty easy and just ship the container ourselfs

**Comment by pimjansen** [comment]
@bram-pkg we use the internal builder as well for the extensions right? So i guess we can ensure we can iterate? Maybe just ensure people can extend the builder in case they want their own

**Comment by bram-pkg** [comment]
We do, yes. I think we can make our own container interface that extends the psr/container.
