### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by olivernybroe** [FakerPHP/Faker#44]
As Faker is now an organisation, I think it makes sense that faker get's its very own logo 🥇

**Comment by pimjansen** [comment]
Can you create one?

**Comment by olivernybroe** [comment]
I don't think @caneco would mind it 😄  He is the logo master. 

Just wanted to hear if there were any interest in this getting a logo first.

**Comment by pimjansen** [comment]
Yeah we talked about it and it looks a bit blank isnt it 😂

Any ideas from the rest of the people?

**Comment by caneco** [comment]
@olivernybroe you're far too kind… 😅

Regarding any logo… what could be a good fit? 🤔

**Comment by olivernybroe** [comment]
As the plugin is inspired by ruby's faker, we could maybe be inspired by their logo? But really make it our own?
![](https://user-images.githubusercontent.com/36028424/40263395-4318481e-5b44-11e8-92e5-3dcc1ce169b3.png)

Maybe a mask like they have, but making it look like an elePHPant?

**Comment by pimjansen** [comment]
What about an elephant with a mask? And no, now covid mask 😂

**Comment by bramceulemans** [comment]
or one of those phony nose / mustache things

**Comment by emiliopedrollo** [comment]
> or one of those phony nose / mustache things

It's funny, but i don't think it would fool anyone, thus not a good enough to "fake" your identity...

**Comment by localheinz** [comment]
I wouldn’t mind paying for a decent logo.

**Comment by bramceulemans** [comment]
> I wouldn’t mind paying for a decent logo.

Me neither. I don't like the current empty icon we currently have.

**Comment by bramceulemans** [comment]
I made a temporary placeholder, maybe we can use this for the time being?

![faker-icon](https://user-images.githubusercontent.com/13304739/101285030-6534e000-37e3-11eb-979f-cd4b741217f1.png)

**Comment by pimjansen** [comment]
> I made a temporary placeholder, maybe we can use this for the time being?
> 
> 
> 
> ![faker-icon](https://user-images.githubusercontent.com/13304739/101285030-6534e000-37e3-11eb-979f-cd4b741217f1.png)
> 
> 

Let's wait till Monday if there is some reply on the socials. If not I agree though.

But also colour definition etc belongs to the design so

**Comment by bramceulemans** [comment]
> But also colour definition etc belongs to the design so

Do you mean a style guide?

**Comment by pimjansen** [comment]
> > But also colour definition etc belongs to the design so
> 
> 
> 
> Do you mean a style guide?

Well style guide for goes a bit far but indeed. We want our docs and such to match a certain schema I guess

**Comment by bramceulemans** [comment]
Yes, I can change it to the same color as the docs.

**Comment by caneco** [comment]
This is probably a long shot… But what do you think of this monogram?

![image](https://user-images.githubusercontent.com/502041/101328890-868bdf80-3868-11eb-971e-72e81e6cd6ae.png)

**Comment by tomasnorre** [comment]
I like the purple one.

**Comment by pimjansen** [comment]
> I like the purple one. 

Me too. Maybe we should add the pho logo in the hat to make sure it's php?

**Comment by localheinz** [comment]
Quick heads-up: I have paid a designer $xxx for a logo design.

Let's see what they come up with; perhaps it is something you will like.

**Comment by caneco** [comment]
@localheinz no worry :)

Let's see… keep us posted! 😉

**Comment by emiliopedrollo** [comment]
I liked the purple one as well. I don't think that the php logo is necessary, it would scale bad when using a small version and would make things unnecessary complicated regarding licenses.

**Comment by bramceulemans** [comment]
I like the monogram, but let's see what @localheinz's designer comes up with.

**Comment by pimjansen** [comment]
@localheinz already got an update?

**Comment by localheinz** [comment]
@pimjansen 

Yes, I have some proposals, but I don't like them - I'll probably consider the money spent a gift.

Go ahead and pick something you like!

**Comment by bramceulemans** [comment]
In that case my preference goes to the monogram one, @localheinz 

Should we vote on Slack?

**Comment by pimjansen** [comment]
> In that case my preference goes to the monogram one, @localheinz 
> 
> 
> 
> Should we vote on Slack?

Yeah agree

**Comment by caneco** [comment]
`let` me know if you need something then 😇

**Comment by pimjansen** [comment]
> `let` me know if you need something then 😇

I think the voting turns out to the black one. Do we have an svg for it or anything? 

Guess we can best put this in a seperate repo right?

**Comment by caneco** [comment]
The black one? The reason behind the three colours it was to see how it could work in different backgrounds 😅

But I'm glad that you like it 🤓

> Guess we can best put this in a seperate repo right?
Maybe… like `/FakerPHP/art`? So I can PR all the assets?

And I'll also PR an update to the README file in this repo 😉

**Comment by pimjansen** [comment]
I added the repo.

**Comment by pimjansen** [comment]
@caneco are you able to add those assets? Would be great to start the next year with a proper identity

**Comment by caneco** [comment]
@pimjansen let's agree on "next week"? 🎅

**Comment by pimjansen** [comment]
> @pimjansen let's agree on "next week"? 🎅 

Haha no rush, just curious 😎

Enjoy the holidays and thanks for the effort!

**Comment by pimjansen** [comment]
Thanks all for the effort!

**Comment by caneco** [comment]
> Thanks all for the effort!

My pleasure 😊
