### ISSUE TITLE
Potential performance issue with v1.19.0

### ISSUE THREAD

**Issue by hhamon** [FakerPHP/Faker#449]
### Summary

The recent upgrade of Faker PHP from v1.18.0 to v1.19.0 seems to have significant performance impact on our CI pipeline.

I'm still unsure whether or not the problem is due to Faker PHP or to the Gitlab CI Pipeline infrastructure itself.

However, after we upgraded to Faker v1.19.0 yesterday, the PHPUnit tests suite (4550+ tests) takes 40% time more to run. With Faker v1.18.0, our PHPUnit job takes around 11 minutes in total while it now takes more than 17 minutes with Faker 1.19.0.

We have a timeout limit at 45 minutes for all our CI jobs (PHPUnit, Cypress, etc).

After upgrading to Faker 1.19.0, our merge requests are timing out reaching the 45 minutes limit.

With Faker 1.18.0, they usually run the whole CI pipeline in ~30 minutes.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.0.x   |
| `fakerphp/faker`  | 1.19.0   |

### PHPUnit CI Job with downgrade to Faker v1.18.0

![Screenshot 2022-02-03 at 10-18-38 phpunit (#740264) · Jobs · BSN Sports TAL Rebuild](https://user-images.githubusercontent.com/235550/152319739-55b77304-f6c2-41f8-8497-942170954915.png)

### PHPUnit CI Job with upgrade to Faker v1.19.0

![Screenshot 2022-02-03 at 10-18-23 phpunit (#739882) · Jobs · BSN Sports TAL Rebuild](https://user-images.githubusercontent.com/235550/152319887-07b4c5c0-2b06-423e-8106-bdac98543402.png)

### Conclusion

I'm still investigating if problem comes from Faker PHP, the Gitlab infrastructure or our application but for now clues lead to Faker PHP.

**Comment by hhamon** [comment]
Strangely, the bot that automatically opens MR to upgrade outdated dependencies opened a MR to upgrade Faker to v1.19.0 while I was writing down this issue. The MR went through the whole CI pipeline in about ~30 minutes and the PHPUnit job took a little bit more than 10 minutes itself to run.

![Screenshot 2022-02-03 at 11-02-10 phpunit (#740342) · Jobs · BSN Sports TAL Rebuild](https://user-images.githubusercontent.com/235550/152321465-12fd0566-83a6-4810-93d4-44a462709ea8.png)

This could probably demonstrate the slowness issue we experienced yesterday evening and this morning are not due to Faker but probably to the Gitlab infrastructure itself.

**Comment by pimjansen** [comment]
If i closely look at the releasenotes of 1.19 there is also really nothing that could impact it.

Some return types got set and a new class is added that is only experimental and never invoked. The only thing that could hit is is the doctrine orm integration.

Are you using that?

**Comment by hhamon** [comment]
Yes we're based on the latest Doctrine 3.x

**Comment by pimjansen** [comment]
> Yes we're based on the latest Doctrine 3.x

Ok well then it should be fine where change was for legacy orm mainly. 

But in your last test it was the runner?

**Comment by hhamon** [comment]
> But in your last test it was the runner?

I don't know! All tests use the same runner so maybe the runner was acting slower for a couple of hours between yesterday and this morning.

**Comment by hhamon** [comment]
Closing for now as it seems we had a temporary CI issue. Sorry for the noise!

**Comment by bram-pkg** [comment]
No problem, glad it got resolved.
