### ISSUE TITLE
DateTime not same, when using same seed in testst

### ISSUE THREAD

**Issue by timohund** [FakerPHP/Faker#453]
### Summary

Hi, 

maybe not a bug, but i am not sure. When i use fake with a seed in testcases if would expect to allways get same dates with the same seed

Depending on the system date is get different results on different days (the is allways an offset of 1 day)

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.0.2   |
| `fakerphp/faker`  |1.19.0  |

### Self-enclosed code snippet for reproduction

```php
 $faker = Factory::create();
 $faker->seed(4711);
 $faker->dateTimeThisDecade()->format('Y-m-d 00:00:00');
```

**Comment by bram-pkg** [comment]
This is correct, since the seed always generates the same offset to the current time range defined in `dateTimeThisDecade`. The same applies for all date generation functions.

Check this PR to see some test examples.

**Comment by timohund** [comment]
@bram-pkg for what do i need a seed then in that case?

**Comment by bram-pkg** [comment]
Numbers, text, anything else that's not relative to current time.
