### ISSUE TITLE
Lazyload locales (Customize load different locale files)

### ISSUE THREAD

**Issue by xiaohuilam** [FakerPHP/Faker#46]
Lazyload(or require/install whatever) locales (Customize load different locale files).
A good advice is composer subpackage...

For example:
Init default english_US faker:
```bash
composer require fakerphp/faker
```

Install Chinese_CN locale:
```bash
composer require fakerphp/zh_CN
```

**Comment by GlennM** [comment]
Isn't this the mono-/multirepo discussion in https://github.com/FakerPHP/Faker/issues/15

**Comment by pimjansen** [comment]
Its already under discussion as mentioned for Faker 2.x which will be a next major.
