### ISSUE TITLE
Cloudflare is back on placeholder.com

### ISSUE THREAD

**Issue by Balsakup** [FakerPHP/Faker#462]
### Summary

Hi, Cloudflare is back on placeholder.com, image generation no longer works.  
Same as https://github.com/FakerPHP/Faker/issues/299

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.0   |
| `fakerphp/faker`  | 1.19.0   |

### Self-enclosed code snippet for reproduction

```php
$this->faker->image
```

**Comment by bram-pkg** [comment]
Since relying on this external service seems to be unstable, I recommend switching to `Faker->randomElement()` for now.

You can put an array in there with some paths to images stored in your testing folder.

**Comment by Okipa** [comment]
@bram-pkg This can be done for new projects indeed.

But this is an unsatisfactory solution for large existing projects, as moving all test suites to this workaround would take hours or days.

The only reliable, long-term solution I see would be a plugin that takes care of image generation.

This solution was considered on this issue https://github.com/FakerPHP/Faker/issues/299.

Is this still the case ?

**Comment by GrahamCampbell** [comment]
Closing as per the discussion.
