### ISSUE TITLE
Feature json data

### ISSUE THREAD

**Issue by zsoltjanes** [FakerPHP/Faker#463]
### Summary

In some project I need random generated json data for tests. What do you think about new json faker feature?

### Solution
The function can has 3 parameter. 
1. the value type (int, boolean, flaot, word, sentence...)
2. counter how many items can be in json
3. level: single or multi level or a number how deep the level shoud be

#### Example code:
```php
$this->faker->json('sentence', 4, 'single')
```

Output:
```php
{
    "first": "Lorem ipsum.",
    "second": "Lorem ipsum.",
    "third": "Lorem ipsum.",
    "forth": "Lorem ipsum."
}
```

#### Example 2 code:
```php
$this->faker->json('word', 2, 'multiple')
```

Output:
```php
{
    "first": {
       "first": "some",
       "second": "word"
   }
}
```

#### Example 3 code:
```php
$this->faker->json('int')
```

Output:
```php
{
   "first": 875,
   "second": 543
}
```

**Comment by pimjansen** [comment]
Imo this not really does it for me. Add stuff from generates in an array and json_encode it instead. It gives you so much more flexibility.

If not feel free to write a custom provider to inject

**Comment by zsoltjanes** [comment]
Okay than what do you think about as you mention just pass an array like: `$this->faker->json($array)`? This should only call the json_encode and maybe that looks better. If you think it doesn't make any sense just close this issue. :)

**Comment by pimjansen** [comment]
> Okay than what do you think about as you mention just pass an array like: `$this->faker->json($array)`? This should only call the json_encode and maybe that looks better. If you think it doesn't make any sense just close this issue, it was just an idea. :)

This would mean that Faker would be a wrapper for json_encode? Just stick with native php in this case
