### ISSUE TITLE
Allow image extension to be set in image() and imageUrl()

### ISSUE THREAD

**Issue by CalebDW** [FakerPHP/Faker#472]
The Placeholder API allows for the following image formats
- .GIF
- .JPG
- .JPEG 
- .PNG

However, the image functions currently default to `png`. It would be an easy fix to add another argument for the extension.

Thanks!

**Comment by pimjansen** [comment]
Agree if we can do this without BC. Feel free to contribute.

**Comment by CalebDW** [comment]
Implemented in PR #473.
