### ISSUE TITLE
Faker::image returns false

### ISSUE THREAD

**Issue by rudashi** [FakerPHP/Faker#476]
### Summary

When using $faker->image(), got always false.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | ALL   |
| `fakerphp/faker`  | 1.19.0   |

### Self-enclosed code snippet for reproduction

```php
$faker->image($path, 250, 250, null, false);
```

### Expected output

```txt
// string with image path
```

### Actual output

```txt
// false
```

### Possible problem

Line 115 from src/Faker/Provider/Image.php returns false.
Function returns HTTP code 403

```
curl_getinfo($ch, CURLINFO_HTTP_CODE)
```
![image](https://user-images.githubusercontent.com/5038647/171344082-3aa1d0fd-cda4-4b24-b9b9-ec04e7744a95.png)

**Comment by bram-pkg** [comment]
Related to: https://github.com/FakerPHP/Faker/issues/475
