### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by jakublabno** [FakerPHP/Faker#486]
Are you planning to add PHP 8.1 compatibility soon?

**Comment by pimjansen** [comment]
It is already compatible? If not please provide a bug report

**Comment by localheinz** [comment]
@jakublabno 

`fakerphp/faker` already supports PHP 8.1, see [`composer.json`](https://github.com/FakerPHP/Faker/blob/v1.19.0/composer.json#L17).
