### ISSUE TITLE
Phone E164 error

### ISSUE THREAD

**Issue by pcomble** [FakerPHP/Faker#487]
### Summary

Generate phone number E164 with local French is wrong.
The actual patern is '+33##########', but they are one extra number.
In french, the phone E164 is '+33[1-9]########'.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.3   |
| `fakerphp/faker`  | 1.19.0   |

### Self-enclosed code snippet for reproduction

```php
$faker->addProvider(new Faker\Provider\fr_FR\PhoneNumber($faker));
echo $faker->e164PhoneNumber
```

### Expected output

```txt
+33866394976
```

### Actual output

```txt
+338663949769
```

**Comment by pimjansen** [comment]
As far as i can see you are right. Feel free to raise a PR
