### ISSUE TITLE
Exactly same result after calling faker methods

### ISSUE THREAD

**Issue by khalilst** [FakerPHP/Faker#492]
### Summary

I'm using faker in the Laravel testing.
After calling `sentence()` or `text()` method, I've got the exact same result.
For example for `sentence()` method, I have this result in every call:
```
Enim odio totam nulla vel corporis fugiat rerum.
```
Interestingly, the result is exactly the same in different machines!!!
Is it working with something like branch hash?

Similar thing for `text()` method:
```
Odio totam nulla vel corporis. Rerum ducimus sunt quidem velit dicta. Temporibus sed esse error et voluptatem perferendis. Ratione dolorum aut eaque.
```

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1.7   |
| `fakerphp/faker`  | ^1.13   |

**Comment by pimjansen** [comment]
Please provide a code snippet to reproduce it

**Comment by khalilst** [comment]
@pimjansen I'm using faker in the Laravel Testing using `WithFaker` trait.
Example Code:
`$this->faker->sentence()`

@DvDty I didn't see any seeding in the Laravel. I've added the seeding in the Laravel code but still have the same result.
Every time it returns exactly the same thing.
I'm wondering what kind of mechanism is used by `Generator`.
Same results even from two different machines!!!

**Comment by khalilst** [comment]
@DvDty I've tried to create the `faker` manually and it generates random texts even without seeding.
I have to confirm it happens only in our code base and even in the fresh Laravel project, it is working fine.
But do you have any idea what can be a cause for such an issue?

**Comment by khalilst** [comment]
I'm closing this issue because it was related to my code and there is nothing wrong with PHPFaker or Laravel.
