### ISSUE TITLE
faker->text() uses 'join' with wrong order of arguments 

### ISSUE THREAD

**Issue by kfheigel** [FakerPHP/Faker#496]
### Summary

Using faker->text() generates 
`TypeError: join(): Argument #2 ($array) must be of type ?array, string given
`
in several places of /app/vendor/fzaninotto/faker/src/Faker/Provider/Lorem.php file. 
### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1   |
| `fakerphp/faker`  | 1.19   |

### Self-enclosed code snippet for reproduction

```php
`    public function getReport(string $jobId): string
    {
        return $this->faker->text;
    }`
```

The problem lies in Lorem.php file where in several places exists 
`return join($words, ' ') . '.';`
![image](https://user-images.githubusercontent.com/21203271/178465279-8a38f036-7540-4fe5-ab6e-691b0278b5f8.png)

which should be 
`return join(' ', $words) . '.';
`
![image (1)](https://user-images.githubusercontent.com/21203271/178465328-5db90acc-d58c-48d0-8468-cfe3674e6e15.png)

**Comment by pimjansen** [comment]
Your error path indicates that you are not using fakerphp but the original fork.

Can you check that first?

**Comment by kfheigel** [comment]
You're right, apparently I've downloaded the older package. Sorry!
