### ISSUE TITLE
Hungarian name generation is broken

### ISSUE THREAD

**Issue by mmarton** [FakerPHP/Faker#502]
### Summary

Hungarian name generation is broken, with the message:

> Unknown format "lastNameFemaleMarried"  In Generator.php line 731

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1 |
| `fakerphp/faker`  | 1.20   |

### Self-enclosed code snippet for reproduction

```php
class UserFixtures extends Fixture
{
    protected Generator $faker;

    public function __construct()
    {
        $this->faker = Factory::create('hu_HU');
    }

    public function load(ObjectManager $manager): void
    {
        $user = (new User)->setName($this->faker->name());
        $manager->persist($user);
        $manager->flush();
    }
}
```

### Expected output

```txt
no error
```

### Actual output

```txt
error
```
possibly caused by of https://github.com/FakerPHP/Faker/pull/451

cc [zsoltjanes](https://github.com/zsoltjanes) as the author of said PR

**Comment by pimjansen** [comment]
I am not able to reproduce this on the `main` branch of Faker. This is the snippet i used matching yours:

```php
<?php
require 'vendor/autoload.php';

$faker = Faker\Factory::create('hu_HU');

for ($i = 0; $i < 1000; $i++) {
    echo $faker->name() . PHP_EOL;
}
```

Anything you missed there?
