### ISSUE TITLE
Suggestions additional features for PHP Framework and PHP Version.

### ISSUE THREAD

**Issue by getsolaris** [FakerPHP/Faker#504]
I'm a good user of the Faker library.

I suggest additional features for PHP Frameworks and PHP Version.

If you are interested in developing a function, I would like to contribute to that function.

Thank you.

**Comment by DvDty** [comment]
Hello 👋
What features do you suggest? You might be interested in version 2.0's development. Check the discussion [here](https://github.com/FakerPHP/Faker/discussions/15).
On the topic of PHP versions, the package supports everything that's currently released and supported.

**Comment by getsolaris** [comment]
@DvDty Thank you !
