### ISSUE TITLE
Get country code with country name

### ISSUE THREAD

**Issue by JercSi** [FakerPHP/Faker#506]
### Summary

I would like to have a method where faker returns an country name and it's country code. Currently it's not possible to get the correct country name for random ISOcode (or other way around).

### Self-enclosed code snippet for reproduction

In this case i will not get matching country name and ISO. So, I might get `country='Germany'`, `ISO='JPN'`.
```php
$country = [
  'name' => $faker->country, // Random country name
  'iso3' => $faker->countryISOAlpha3 // Random ISO
];
```

Something like this would solve my problem.
```php
$countryData = $faker->countryData();

$country = [
  'name' => $countryData['country'], // Germany
  'iso2' => $countryData['countryCode'] // DE
  'iso3' => $countryData['countryISOAlpha3'] // DEU
];
```

### Expected output

```txt
Method to get country with matching name, ISO,... 
```

### Actual output

```txt
Random country, random ISO, random country code.
```

**Comment by pimjansen** [comment]
I dont think it is worth embedding this in Faker. For 2.x a community extension can be created though but overall its just a proxy for

https://packagist.org/packages/league/iso3166

Just call the all method and grab a random element from the array

**Comment by pimjansen** [comment]
From the other hand i do like the idea to add a method to bundle the matching data but i dont think we store that at this point

**Comment by JercSi** [comment]
> I dont think it is worth embedding this in Faker. For 2.x a community extension can be created though but overall its just a proxy for
> 
> https://packagist.org/packages/league/iso3166
> 
> Just call the all method and grab a random element from the array

Thanks. I think this package will solve my problems :)

**Comment by pimjansen** [comment]
The only thing it does not do is localize it. But doing it in Faker would be pretty messy where you have to duplicate a lot of data to all language packs

**Comment by JercSi** [comment]
I didn't dig into the code, but i think there could be only few changes. But this could be a breaking changes.

I guess: (localized) `$country` array should be converted into associative array with keys as a ISOAlpha3
```php
 protected static $country = [
  'Afghanistan',
  'Albania',
  'Algeria',
  ...
];
```
into
```php
 protected static $country = [
  'AFG' => 'Afghanistan', 
  'ALB' => 'Albania',
  'DZA' => 'Algeria',
  ...
];

// Get country
public static function getCountryData() 
{
  $iso = static::randomElement(static::$countryISOAlpha3);
  
  return [
    'iso' => $iso,
    'name' => static::$country[$iso] ?? ''
  ]; 
}
```

**Comment by pimjansen** [comment]
Yeah that would work for a global value but the country list is localized. That means you have to maintain the same list for all countries and im not sure if thats smart.

Faker states that it creates fake data but not that it always be valid.
