### ISSUE TITLE
How to set locale?

### ISSUE THREAD

**Issue by tacman** [FakerPHP/Faker#509]
```php
        $generator = Faker\Factory::create();
        echo $generator->address(); 
```

Is there a way to set the generator, or set the address call, so that it's a specific locale?  That is, how would I get a German address or company name?

**Comment by pimjansen** [comment]
Please read the documentation:

https://fakerphp.github.io/#localization

**Comment by tacman** [comment]
Thanks!  I kept looking under Locale.  (head-smack).
