### ISSUE TITLE
Unknown format "lastNameFemaleMarried"

### ISSUE THREAD

**Issue by albertborsos** [FakerPHP/Faker#510]
### Summary

I get the following exception if I use the `$faker->name` property/method.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.3   |
| `fakerphp/faker`  | 1.20.0   |

### Self-enclosed code snippet for reproduction

```php
\Faker\Factory::create('hu_HU')->name
```

### Expected output

```txt
a random hungarian name
```

### Actual output

```txt
[InvalidArgumentException] Unknown format "lastNameFemaleMarried"  
```

**Comment by pimjansen** [comment]
If im correct this is already fixed. Could you verify main?

**Comment by albertborsos** [comment]
Yes it is fixed in main, but a stable release would be great.
