### ISSUE TITLE
Immutable date times?

### ISSUE THREAD

**Issue by jmsche** [FakerPHP/Faker#512]
Hi,

In some projects I have to feed \DateTimeImmutable objects instead of \DateTime objects.

Would you accept a PR adding eg. a DateTimeImmutable provider extending the existing DateTime provider?

**Comment by pimjansen** [comment]
Faker generates the data though. I guess its just as easy to use native php here?

https://www.php.net/manual/en/datetimeimmutable.createfrommutable.php

**Comment by jmsche** [comment]
While it's okay to do this using eg. zenstruck/foundry (which uses PHP), it's quite harder to do so with nelmio/alice that uses YAML, hence my question :)

**Comment by pimjansen** [comment]
I have put it as discussion on the Faker slack channel. However its also something where Alice could change (i dont know the lib at all).

@bram-pkg thoughts? Since there will always be "something" with dates im affraid

**Comment by pimjansen** [comment]
> Hm, I am not opposed to having our dates be returned as immutable objects.


Fair but i would mean a BC. I would vote in favor too. What we can do is implement the method and deprecate the old ones for the next minor. We then change it on the new major to only have immutables.

What do you think?

**Comment by pimjansen** [comment]
Well i do not see this happening since its a BC on 1.x

**Comment by dereuromark** [comment]
Would be great to have immutable available somehow
The side effects of accidently touching a datetime and it affecting previous test data setup is immense.

**Comment by antoinelucas-dev** [comment]
> Maybe we can keep the current DateTimeProvider intact & add a DateTimeImmutableProvider?

Hi,

Would it be possible to add this solution ?
