### ISSUE TITLE
Can't get a image

### ISSUE THREAD

**Issue by luismorales1991** [FakerPHP/Faker#514]
When you use $faker->image(x,x,x), it doesn't download the image, and that's because:
`copy(xxx): Failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden`
The link is forbidden so it doesn't get anything and doesn't throw any error.

1. It's possible to throw an Error at the cURL's part
2.  It's possible to find a way (trying to avoid the "headers trick", unless that's the way, I apologize) to get images without the 403 error

If there's a correct way I'm missing, I'd like to know

**Comment by pimjansen** [comment]
The image method is deprecated. Please use a third party plugin instead

**Comment by pimjansen** [comment]
See https://github.com/FakerPHP/Faker/issues/475
