### ISSUE TITLE
UUID versions?

### ISSUE THREAD

**Issue by alejgarciarodriguez** [FakerPHP/Faker#515]
Hi, I wonder if it would be possible to generate valid UUID for a specific version (v3, v4, v5...) with this library.

Should I create a new custom formatter for this?

Thanks

**Comment by pimjansen** [comment]
Getting a valid uuid is a job on its own. I suggest using ramsey uid instead to generate those.

What is also possible to add a faker extension that proxies this

**Comment by alejgarciarodriguez** [comment]
I suggest something like:

```php
$faker->uuidv4()
$faker->uuidv5()
```

and let the current uuid as is

**Comment by pimjansen** [comment]
I'd rather think the uuid integration would fully be removed from Faker and an extention would be created that uses a native package like ramsey where you can generate all valid uuid.

There is no need for Faker to add a custom uuid integration which would probably generate invalid data as well
