### ISSUE TITLE
Invalid time zone name

### ISSUE THREAD

**Issue by igorpopryadukhin** [FakerPHP/Faker#520]
### Summary

```php
$tz = Faker::instance()->timezone(); // Europe/Kyiv o_O
```
~~Europe/Kyiv~~
Europe/Kiev

**Comment by pimjansen** [comment]
According the documentation it is valid. See https://www.php.net/manual/en/timezones.europe.php

Why do you think its wrong?

**Comment by igorpopryadukhin** [comment]
php 7.4

```php
foreach (timezone_identifiers_list() as $item) {
	echo $item . PHP_EOL;
}
```

I can not find "Europe/Kyiv" 

![image](https://user-images.githubusercontent.com/48174353/193021244-73fa5882-eb4c-4ab1-b8d9-0b48e5d5202a.png)

**Comment by igorpopryadukhin** [comment]
php 8.1 - Europe/Kyiv
php 7,4 - Europe/Kiev

**Comment by igorpopryadukhin** [comment]
https://bugs.php.net/bug.php?id=80254
