### ISSUE TITLE
Invalid person name

### ISSUE THREAD

**Issue by acuto5** [FakerPHP/Faker#521]
https://github.com/FakerPHP/Faker/blob/42fa8b94cd75c823131a581eb1cf0e24b9a3bbde/src/Faker/Provider/lt_LT/Person.php#L241

It should be "Kazlauskas", not "Kazlaukas".

**Comment by pimjansen** [comment]
Do we have some reference for this?

**Comment by Kenny-MWI** [comment]
For what it's worth, [this page](https://surnames.behindthename.com/name/kazlauskas/) claims Kazlauskas is the most common surname in Lithuania. Google gives this message when I search for `lithuania name Kazlaukas`: "Showing results for `lithuania name Kazlauskas`"

[Here's the Wikipedia page for Kazlauskas](https://en.wikipedia.org/wiki/Kazlauskas).

**Comment by pimjansen** [comment]
Ok thanks, can you raise a PR for this topic?
