### ISSUE TITLE
Can not save image locally

### ISSUE THREAD

**Issue by s96Abrar** [FakerPHP/Faker#522]
#### `Faker::image()` can not save image locally

After walking through the code of faker when I stop deleting (commenting `unlink()`) the downloaded file from `via.placeholder.com`, it seems it returns a HTML file. The file contains a message saying, 
```
error code: 1020
```

After checking bit more, I added the `USER_AGENT` option for curl and it returns a different html fie saying,
```
Please enable cookies.
Sorry, you have been blocked
You are unable to access placeholder.com
...
```

It seems cloudflare is blocking access for curl and treating it as bot but accessing the same url in browser works fine.

**Comment by pimjansen** [comment]
See related issues. The feature is deprecated and we suggest using a third party extension for this
