### ISSUE TITLE
CC-BY-SA-NC license notice in it_IT Text

### ISSUE THREAD

**Issue by spiess-demos** [FakerPHP/Faker#524]
While Faker is licensed under MIT, the [it_IT Text contains a license notice](https://github.com/FakerPHP/Faker/blob/main/src/Faker/Provider/it_IT/Text.php#L29) that indicates a CC-BY-SA-NC license which makes it incompatible to otherwise licensed software. 

As the original author mentions in [a similar issue in the archived Faker](https://github.com/fzaninotto/Faker/issues/881), the text ("Pinocchio" by Carlo Collodi) can be assumed to be [public domain](https://en.wikipedia.org/wiki/Public_domain). The publisher mentioned in the text (Liber Liber) [notes on his website](https://www.liberliber.it/online/opere/libri/licenze/) that the license applies to the cover and layout.

I'd suggest to remove the license notice from the text.

**Comment by pimjansen** [comment]
In this case i think we should remove the data from Faker or fine a replacement. We cant just ignore a license by removing it
