### ISSUE TITLE
Generate postcode without formatting in 'pt_BR' provider

### ISSUE THREAD

**Issue by danie1net0** [FakerPHP/Faker#527]
Using the 'pt_BR' provider, it is possible to generate CPF or CNPJ without formatting, passing a boolean to the method. But the `postcode` method does not have this parameter and in some cases it is useful to generate just the postcode number, like in database integration tests where only the numbers are stored. Example:

This method: `$this->faker->postcode(false);` will return an unformatted postcode: `00000111`, instead of: `00000-111`.

I think about doing this implementation, but I would like your opinion so I don't spend time on a PR that will be rejected.

**Comment by pimjansen** [comment]
In Faker 2.x its interface bound so customizing is not something that would work here

**Comment by danie1net0** [comment]
Ok, thak you.
