### ISSUE TITLE
Should Providers fall back to en_US if an entry isn't found? 

### ISSUE THREAD

**Issue by gomako** [FakerPHP/Faker#529]
### Summary

I'm using en_GB as a provider and when I generate a jobTitle I get a single lorem ipsum word. In the en_US provider there is an array of job titles, but not in the en_GB provider. Should Faker fall back to en_US if it can't find an entry?

Sorry if I'm doing this wrong, I don't contribute to many projects!

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1.4   |
| `fakerphp/faker`  | 1.9.1   |

### Self-enclosed code snippet for reproduction

```php
$faker = Faker\Factory::create('en_GB');
$faker->jobTitle();
```

### Expected output

```txt
Optometrist
```

### Actual output

```txt
dolorum
```

**Comment by pimjansen** [comment]
Yes for 1.x it will if im correct

**Comment by gomako** [comment]
Ok, it's not doing it at the moment. I am working around it by creating a new factory with the default provider which is fine. Rather than duplicate the providers in the en_GB one I'll try and find the place where the fallback happens in the code and create a PR.

**Comment by pimjansen** [comment]
Well i have to check since im not really sure. Imho it should be valid that there is no fallback since each locale lives on its own. It does not make sense to return an en_us field for an it_it locale

**Comment by gomako** [comment]
I have just tried to reproduce this by downloading this repo, by doing the following:
````
git clone git@github.com:FakerPHP/Faker.git
composer install
````
Then made the following test script:
````
<?php
require_once('vendor/autoload.php');
$faker = Faker\Factory::create('en_GB');
echo $faker->jobTitle();
````
Which output `Telemarketer `!

So I think the error must be in my installation. I am using Laravel which comes with Faker (`"fakerphp/faker": "^1.9.1",` in the composer.json). So I will close this issue, sorry!.
