### ISSUE TITLE
e164PhoneNumber() generates invalid french Phone Numbers

### ISSUE THREAD

**Issue by MedericL-cgi** [FakerPHP/Faker#531]
### Summary

Similar issue : #332
Using e164PhoneNumber(), an invalid number is created for fr_FR. The generated phone numbers that start with 0 are invalid.
Ex : +330123456789

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1.11   |
| `fakerphp/faker`  | 1.20.0   |

### Self-enclosed code snippet for reproduction

```php
$faker = FakerFactory::create();

dump($faker->e164PhoneNumber());
```

### Expected output

number with +33[1-9]#########

### Actual output

number with +33[0-9]#########

Source :   
https://en.wikipedia.org/wiki/Telephone_numbers_in_France

**Comment by MedericL-cgi** [comment]
In case someone find this thread, we don't use 'e164PhoneNumber' anymore.
Instead, we use <regexify(((\+)33((?6\d|7[3-9])\d{7})> in alice fixtures files.

**Comment by mergeMarc** [comment]
I noticed the same with invalid swiss (de_CH) phone numbers. Would be nice if faker would offer more strict phone number generation.

**Comment by DvDty** [comment]
@mergeMarc Have you tried generating a number via [numerify()](https://fakerphp.github.io/formatters/numbers-and-strings/#numerify)?

**Comment by mergeMarc** [comment]
I could use numerify but only with the last few digits being random. The application i generate fixtures for has more strict validation (with [libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php)) so things like area codes also need to be valid.

Using numerify would definitely be a valid workaround if only a smaller subset of possible phone numbers is needed (also randomly selecting from multiple numerify inputs). Probably less expensive than some regexify stuff too.

**Comment by mergeMarc** [comment]
I would still be interested in this. Only issue i could see is that this would require a full on reverse regex type of solution to generate phone numbers based on commonly used metadata (like [googles libphonenumber](https://github.com/google/libphonenumber)). So it might be overkill for some use cases.

My current workaround uses a reverse regex library with a static regex to generate plausible phone numbers for a country.
Example regex for swiss phone numbers (extracted from libphonenumber):
```
\+41((2[12467]|3[1-4]|4[134]|5[256]|6[12]|[7-9]1)\d{7}|7[35-9]\d{7})
```
