### ISSUE TITLE
php-cs-fixer does not support version 8.1.

### ISSUE THREAD

**Issue by sajaddp** [FakerPHP/Faker#537]
### Summary

When I run `make cs` command, I get the error of not supporting version 8.1.

```
PHP needs to be a minimum version of PHP 7.1.3 and maximum version of PHP 8.0.*.
Current PHP version: 8.1.12.
```

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1.12   |
| `fakerphp/faker`  | 1.20.0   |

**Comment by DvDty** [comment]
It does - https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/composer.json#L17.
Faker's pipeline still [runs it through 7.1](https://github.com/FakerPHP/Faker/blob/main/.github/workflows/coding-standards.yml#L19) though.
How are you adding the package to run it locally? Do you have it as a global composer dependency?

**Comment by pimjansen** [comment]
This is intended. To keep older versions supported we run alit at the oldest supported version.

In fact it is only needed while developing against Faker. If so i suggest just to run it in a docker container

**Comment by sajaddp** [comment]
PHP no longer supports older versions.
What is the need to support versions that are likely to have security issues?

https://www.php.net/supported-versions.php

**Comment by pimjansen** [comment]
> PHP no longer supports older versions.
> 
> What is the need to support versions that are likely to have security issues?
> 
> 
> 
> https://www.php.net/supported-versions.php

7.4 is still in support

**Comment by sajaddp** [comment]
Until `28 Nov 2022` and today is `13 Nov 2022`

> > PHP no longer supports older versions.
> > What is the need to support versions that are likely to have security issues?
> > https://www.php.net/supported-versions.php
> 
> 7.4 is still in support

PHP 7.4 security update until `28 Nov 2022` and today is `13 Nov 2022`.
It will definitely take time to update the package dependency and release the update until this date.

**Comment by pimjansen** [comment]
Correct but there is enough time to handle this? Furthermore the fixer is only intended for development so i would not worry about it at all
