### ISSUE TITLE
Problem in Farsi/Persian Fakers

### ISSUE THREAD

**Issue by rezabagheri** [FakerPHP/Faker#578]
The 

- `paragraph`
- `sentence`
- `text`

functions return English results when using `fa_IR` as locale, regardless of their providers.

```php

use Faker\Factory;

require_once __DIR__ . '/vendor/autoload.php';

$faker = Factory::create('fa_IR');

$faker→seed(1);

var_dump([
    'paragraph' => $faker->paragraph,
    'sentence' => $faker->sentence,
    'text' => $faker->text,
]);
```

## Expected

- results in `fa_IR`

## Actual

- results in `en_US`

**Comment by localheinz** [comment]
@rezabagheri 

Which version of `fakerphp/faker` do you use?
Which values do you pass as `$locale` to https://github.com/FakerPHP/Faker/blob/v1.21.0/src/Faker/Factory.php#L18?

**Comment by rezabagheri** [comment]
I think we have same problem in other languages
when i use 
```
$faker = Factory::create('en_US');
echo $faker->Text();

```
Ouput is: 

> Consequuntur ea iusto est ipsam saepe qui debitis. Aliquid sit corporis rem perspiciatis quia eveniet voluptatum. Aliquam expedita non et. Soluta enim ex sunt.

non english Text!

**Comment by DvDty** [comment]
https://en.m.wikipedia.org/wiki/Lorem_ipsum

**Comment by rezabagheri** [comment]
> https://en.m.wikipedia.org/wiki/Lorem_ipsum

This is related to Lorem Provider, we work with Text provider
And inside this provider there are selected sentences from the book Alice's Adventures in Wonderland
[]((https://github.com/FakerPHP/Faker/blob/main/src/Faker/Provider/en_US/Text.php))
https://github.com/FakerPHP/Faker/blob/main/src/Faker/Provider/en_US/Text.php

**Comment by DvDty** [comment]
I think text points to the Lorem provider.
Try realText()

**Comment by DvDty** [comment]
Text: https://fakerphp.github.io/formatters/text-and-paragraphs/

Real text: https://fakerphp.github.io/formatters/#fakerprovideren_ustext

**Comment by rezabagheri** [comment]
Thanks a lot!
