### ISSUE TITLE
Doctrine ObjectManager namespace has changed

### ISSUE THREAD

**Issue by ElMulot** [FakerPHP/Faker#581]
### Summary

In the last version of Doctrine (2.13), ObjectManager namespace has changed from:
`Doctrine\Common\Persistence\ObjectManager`

To:

`Doctrine\Persistence\ObjectManager`

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1.2   |
| `fakerphp/faker`  | 1.21.0   |

### Possible solutions

Remplace namespace on `Faker\ORM\Doctrine\Populator`

**Comment by pimjansen** [comment]
Can you show us a reproduction example of an actual bug where something goes wrong?

**Comment by SzymonKaminski** [comment]
There's phpstan error at level 5:
`Parameter #2 $manager of class Faker\ORM\Doctrine\Populator constructor expects Doctrine\Common\Persistence\ObjectManager|null, Doctrine\ORM\EntityManagerInterface given.`

`EntityManagerInterface` extends `\Doctrine\Persistence\ObjectManager`, not the `Doctrine\Common\Persistence\ObjectManager` mentioned by OP.

**Comment by pimjansen** [comment]
> There's phpstan error at level 5:
> 
> `Parameter #2 $manager of class Faker\ORM\Doctrine\Populator constructor expects Doctrine\Common\Persistence\ObjectManager|null, Doctrine\ORM\EntityManagerInterface given.`
> 
> 
> 
> `EntityManagerInterface` extends `\Doctrine\Persistence\ObjectManager`, not the `Doctrine\Common\Persistence\ObjectManager` mentioned by OP.

But does the code work? If im correct there are aliases available and the lib should behave fine
