### ISSUE TITLE
[RFC] Only generate safe URLs

### ISSUE THREAD

**Issue by kiler129** [FakerPHP/Faker#585]
### Summary
In one of my recent projects I used the URL generator to populate some fake links in the admin panel. Murphy's low got in the way and one of the testers send me a link showing that one of the test links redirected to explicit materials.

I think the current URL generation logic is slightly unsafe, as it generates domain names based on `lastName`. Since the dataset, by design, contains many real last names a lot of URLs generated exist. 

### Solution
I believe we can introduce a list of safe domain names and keep the URL logic as-is. This will at worst direct users to safe 404 pages. By safe I mean the combination of `safeEmailDomain` + some big names, e.g.:
- `google.{com|biz|org|net}`
- `youtube.com`
- `apple.{com|net}`
- `microsoft.{com|net|org}`
- `cloudflare.{com|net|org}`
- `wikipedia.org`

I would keep the `domainName()` as-is, to ensure if someone is looking to generate many unique domains this is still the case.

WDYT? I can provide PR if this is something you want added.

**Comment by pimjansen** [comment]
The only way to really do this is by owning the domain itself. It was never intended to generate "safe" names but only valid urls.

**Comment by abdulwahedtalash** [comment]
> 

agreed
