### ISSUE TITLE
Error in Base.php while attempting to load fixtures

### ISSUE THREAD

**Issue by dimabredun** [FakerPHP/Faker#592]
### Summary

I'm using Foundry library in symfony project, that provides faker in my Factory classes, but while loading the fixtures getting this error: 

Error In Base.php line 202:
                                                                          
  array_keys(): Argument #1 ($array) must be of type array, string given 

I also tried to use pure faker, but got same result. 

### Versions

|                | Version |
| PHP            | 8.1   |
| `fakerphp/faker`  | 1.16   |

### Self-enclosed code snippet for reproduction

```php
            'address1' => self::faker()->text(65535),
```

### Expected output

```txt
expecting that all the fixtures will be successfully load after and database will be purged after running  :
symfony console doctrine:fixtures:load 
```

### Actual output

```txt
Error:  array_keys(): Argument #1 ($array) must be of type array, string given ```

**Comment by pimjansen** [comment]
Can you post a result of pure faker that throws this error? And did you try upgrading too?

**Comment by dimabredun** [comment]
@pimjansen the same error for pure faker. Just upgraded pure one to 1.21 - same result. Don't know how to upgrade it inside foundry library

**Comment by pimjansen** [comment]
> @pimjansen the same error for pure faker. Just upgraded pure one to 1.21 - same result

Please share a snippet that gives the error

**Comment by dimabredun** [comment]
```
final class UserinfoFactory extends ModelFactory
{
    protected function getDefaults(): array
    {
        return [
            'alert' => self::faker()->text(65535),
            'comment' => self::faker()->text(65535),
            'corporateId' => self::faker()->randomNumber(),
            'createdBy' => self::faker()->randomNumber(),
            'facilityId' => self::faker()->randomNumber(),
            'flag' => self::faker()->text(10),
            'floorId' => self::faker()->randomNumber(),
            'globalUser' => self::faker()->text(10),
            'ipin' => self::faker()->text(10),
            'lastmodified' => self::faker()->dateTime(),
            'linkedUrl' => self::faker()->text(65535),
            'locationId' => self::faker()->randomNumber(),
            'logStatus' => self::faker()->text(10),
            'loginStat' => self::faker()->text(10),
            'mailType' => self::faker()->text(10),
            'pwdFlag' => self::faker()->text(10),
            'quest1Ans' => self::faker()->text(),
            'quest1Id' => self::faker()->randomNumber(),
            'questAns' => self::faker()->text(255),
            'questId' => self::faker()->randomNumber(),
            'sessionId' => self::faker()->text(255),
            'userEmail' => self::faker()->text(65535),
            'userId' => self::faker()->randomNumber(),
            'userName' => self::faker()->text(255),
            'userPass' => self::faker()->text(255),
            'userTitle' => self::faker()->text(255),
        ];
    }
}
```

```
class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
       UserTypeCategoryFactory::createMany(10);
       UserTypeFactory::createMany(20, function () {
           return [
               'category_id' => UserTypeCategoryFactory::random()->getId()
           ];
       });
        UserinfoFactory::createMany(100, function () {
            return [
                'userTypeId' => UserTypeFactory::random()->getId(),
            ];
        });

       FacilityFactory::createMany(100);
       ProviderInfoFactory::createMany(20);

       $manager->flush();
    }
}
```

symfony console doctrine:fixtures:load --env=test

 Careful, database "latticepro_test" will be purged. Do you want to continue? (yes/no) [no]:
 > yes

   > purging database
   > loading App\DataFixtures\AppFixtures

In Base.php line 202:
                                                                          
  array_keys(): Argument #1 ($array) must be of type array, string given

**Comment by pimjansen** [comment]
What does self::faker() do? 

Can you supply an occurrence of the error by using Faker native?

**Comment by dimabredun** [comment]
```
class FacilityFixture extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $facility = new Facility();
        $faker = Factory::create();

        $facility->setFacilityNm($facilityName = $faker->word());
        $facility->setFacilityAliasNm($facilityName);
        $facility->setFacilityType($faker->numberBetween(0,33));
        $facility->setFacilityStat($faker->randomElement('A','i'));

        $manager->flush();
    }
}
```

With pure faker I'm running bin/phpunit (using this functional for tests), returns the same error: 

>   > purging database
>    > loading App\DataFixtures\ApplicationMasterFixture
>    > loading App\DataFixtures\FacilityFixture
> 
> In Base.php line 202:
>  array_keys(): Argument #1 ($array) must be of type array, string given

**Comment by dimabredun** [comment]
> 

Sorry that didn't explain. self::faker() creates dummy value to entity field, it's provided by zenstruck/foundry library, the namespace is Zenstruck\Foundry\ModelFactory

**Comment by pimjansen** [comment]
Your code is wrong. `randomElement` expects an array and not a string.

**Comment by dimabredun** [comment]
@pimjansen yes, that solved it! Thank you so much for the help!
