### ISSUE TITLE
Feature: Have ability to provide HTTPS only URLs

### ISSUE THREAD

**Issue by asdat** [FakerPHP/Faker#593]
### Summary

If framework expects to cooperate with HTTPS urls in 1 of 5 tests runs where we use `$faker->url()` we will have HTTPS URL, in other 4 cases - HTTP. It could lead to some issues when code must follow some high security requirements and prevent cooperation with HTTP URLS allowing only HTTPS.

The main case here is that URL schema is not always same and could considered as a bug.

### Self-enclosed code snippet for reproduction

```php
$faker->url()
```

### Expected output

```txt
https://www.runolfsdottir.com/
```

### Actual output

```txt
http://www.runolfsdottir.com/
```

**Comment by pimjansen** [comment]
See related comment in the PR
