### ISSUE TITLE
Crash when an empty `Traversable` is entered into `randomElements()`

### ISSUE THREAD

**Issue by KentarouTakeda** [FakerPHP/Faker#604]
### Summary

Crash when an empty `Traversable` is entered into `randomElements()`

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.2.3   |
| `fakerphp/faker`  | 1.21.0   |

### Self-enclosed code snippet for reproduction

```php
# replace this with a self-enclosed usage example
BaseProvider::randomElements(new \ArrayIterator(), 0);
```

### Expected output

```txt
# replace this with the expected output of your self-enclosed example

// Empty array should be returned.
```

### Actual output

```txt
# replace this with the actual output of your self-enclosed example
TypeError: array_keys(): Argument #1 ($array) must be of type array, ArrayIterator given

Faker/src/Faker/Provider/Base.php:202
```

**Comment by pimjansen** [comment]
It expects an array and not a traversable. I do not really why this is a bug?

**Comment by KentarouTakeda** [comment]
`randomElements()` are designed to handle `Traversable`. And it actually works (unless it is zero length).
https://github.com/FakerPHP/Faker/blob/v1.21.0/src/Faker/Provider/Base.php#L194-L198

Then i think it should be fixed that it crashes only under certain conditions.

If we want consistency and correctness of behavior, we could remove the `Traversable` implementation and only accept `array`. But that would break a lot of code that has already been written.
