### ISSUE TITLE
timezone() does not respect country code

### ISSUE THREAD

**Issue by jefhar** [FakerPHP/Faker#606]
### Summary

`Faker\Provider\DateTime::timezone()` is missing the optional `$countryCode` that is found in `Faker\Core\DateTime::timezone()`.

This has the effect (in Laravel anyway) that `fake()->timezone('US')` provides a random timezone instead of returning a timezone in the designated country code.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.2   |
| `fakerphp/faker`  | 1.21.0   |

### Self-enclosed code snippet for reproduction

```php
fake()->timezone('US');
```

### Expected output

```txt
"America/Indiana/Knox"
```

### Actual output

```txt
Africa/Algiers
```

**Comment by pimjansen** [comment]
What is fake()? Please report a valid standalone usecase of Faker

**Comment by jefhar** [comment]
@pimjansen:

index.php consists of 
```php
<?php

require_once './vendor/autoload.php';

$countryCode = 'US';
$faker = new \Faker\Provider\DateTime(new \Faker\Generator());

echo 'This timezone should be in ' . $countryCode. ': `' . $faker::timezone($countryCode) . '`' . PHP_EOL;
```

composer.json consists of
```json
{
  "require": {
    "fakerphp/faker": "^1.21"
  }
}
```

Output:
```bash

$ php index.php
This timezone should be in US: `Pacific/Pago_Pago`

```
