### ISSUE TITLE
Placeholder.com is no longer a random image generating site

### ISSUE THREAD

**Issue by browner12** [FakerPHP/Faker#614]
### Summary

https://placeholder.com/ is no longer a random image generating site, but rather a warehouse space searching site (lol).

Currently image generation in this project relies on placeholder.com

https://fakerphp.github.io/formatters/image/

This URL is hardcoded here: https://github.com/FakerPHP/Faker/blob/275f172eba8c4f0bbb588c6303cc95faf6658e14/src/Faker/Provider/Image.php#L13

To fix I would propose we pick a new default random image generating site, and possibly in addition also allow users to customize this.

**Comment by pimjansen** [comment]
The method is already deprecated so i guess we wont change much on it and suggest to create your own provider instead

**Comment by browner12** [comment]
Maybe a deprecated note in the docs?

**Comment by qolarnix** [comment]
+1 this should be fixed

**Comment by crossiatlas** [comment]
For anyone else who found this Issue via Google, currently (as of 29 March 2023) Placeholder is technically still working even though the main website is now for an unrelated Warehousing business.

For example:
`https://via.placeholder.com/640x480.png/004466?text=animals+omnis`
Returns this image:
<img src="https://user-images.githubusercontent.com/123430556/228391783-6154a47a-7ccc-40d6-a6b5-3a22f7dc3d96.png" width="50%" height="50%">

However, we're relying on the generosity of the new owner (assuming it is someone new) to keep this service running, so it wouldn't surprise me if it shutdown at some point.

## Alternatives
(A couple that I found which might be a good starting point for others)

**Faker Images Provider**
https://github.com/morawskim/faker-images
This one includes support for several alternative online image generators, specifically [picsum.photos](https://picsum.photos/), [lorem.space](https://lorem.space/), and [lorem.faces](https://loremfaces.com/)

**Faker Billions Images**
https://github.com/bilions-org/faker-bilions-images
This one uses the GD library to generate simple test images with text, so it doesn't rely on any third-party online services (definitely useful if you're using Faker as part of an automated test suite).

Ideally I'd like to find one which supports both online generates and GD images so I have a choice (GD images for automated tests, online images for my dev environment) but this may not exist.

I'm sure there are many more alternatives out there but that's probably outside the scope of this thread.
