### ISSUE TITLE
Wrong imageUrl docblock

### ISSUE THREAD

**Issue by pascalvgemert** [FakerPHP/Faker#630]
###Version:
v1.21.0 (latest at time of creation)

### Summary
On the following line the imageUrl() docblock is telling me that there are only 6 parameters, see here:
https://github.com/FakerPHP/Faker/blob/e43a73207c7ab3a081c3cd7d2f1df32c06ef33ba/src/Faker/Generator.php#L278

But the method itself uses 7, as stated here: https://github.com/FakerPHP/Faker/blob/e43a73207c7ab3a081c3cd7d2f1df32c06ef33ba/src/Faker/Provider/Image.php#L53

Therefore PHPStorm or any other IDE will show the wrong autocomplete / hints.

### Solution:
`@method string imageUrl($width = 640, $height = 480, $category = null, $randomize = true, $word = null, $gray = false, $format = 'png')`

**Comment by localheinz** [comment]
Thank you for reporting, @pascalvgemert!
