### ISSUE TITLE
non-static function `Person::birthNumber()` called statically (Provider/cs_CZ/Person.php)

### ISSUE THREAD

**Issue by jakubmisek** [FakerPHP/Faker#640]
### Summary

Static function ` Faker\Provider\cs_CZ\Person::birthNumberMale()` calls non-static function `birthNumber()` at

https://github.com/FakerPHP/Faker/blob/da0dad13b0d8432918b1453cc763e04d7364d739/src/Faker/Provider/cs_CZ/Person.php#L481

### Versions

|                | Version |
|:---------------|:--------|
| `fakerphp/faker`  | `main`   |

**Comment by billalxcode** [comment]
Hi, this error is found in the file `Faker/src/Faker/Provider/cs_CZ/Person.php` more precisely on line `435`.

```php
public function birthNumber($gender = null, $minAge = 0, $maxAge = 100, $slashProbability = 50)
{
   // code here
}
```
The code is the wrong code, to fix it please change it to
```php
public static function birthNumber($gender = null, $minAge = 0, $maxAge = 100, $slashProbability = 50)
{
   // code here
}
```

Reference:
1. [PHP: Static Keyword - Manual](https://www.php.net/manual/en/language.oop5.static.php)
2. [Static Function in PHP](https://www.geeksforgeeks.org/static-function-in-php/)

**Comment by DvDty** [comment]
> The code is the wrong code, to fix it please change it to
> `public static function birthNumber`

This wouldn't work, the method references the object through `$this`.

We could change
```
public static function birthNumberMale()
{
    return static::birthNumber(static::GENDER_MALE);
}

public static function birthNumberFemale()
{
    return static::birthNumber(static::GENDER_FEMALE);
}
```
to
```
public function birthNumberMale()
{
    return $this->birthNumber(static::GENDER_MALE);
}

public function birthNumberFemale()
{
    return $this->birthNumber(static::GENDER_FEMALE);
}
```
