### ISSUE TITLE
Person -> taxId() in it_IT not working

### ISSUE THREAD

**Issue by michael-kreatif** [FakerPHP/Faker#643]
Hi guys, 

the taxId() (Codice Fiscale) in Italian is not valid.
The problem occurs, because the last character has to be computed and therefore is not a randomised character.

https://en.wikipedia.org/wiki/Italian_fiscal_code ->Check character (one letter)

Example ( generated over faker api):
```
UVPTVR50J53C641F 
odd chars = UPV5J361 = 16+10+10+13+21+7+15+0 = 92
even chars = VTR05C4  = 21+19+17+0+5+2+4 = 68
160 % 26 = 4
last character should be E
```

**Comment by DvDty** [comment]
I started working on a fix.
Looks like the last digit isn't the only issue - we're generating invalid months (like `J` in your example). The value of the month should be coming from this mapping:

-- | -- 
A | January
B | February
C | March
D | April
E | May
H | June
L | July
M | August
P | September
R | October
S | November
T | December

Another thing:
> odd chars = UPV5J361 = 16+10+10+13+21+7+15+0 = 92
Why is `P = 3` here? Mistake or some special rule?

**Comment by michael-kreatif** [comment]
> I started working on a fix. Looks like the last digit isn't the only issue - we're generating invalid months (like `J` in your example). The value of the month should be coming from this mapping:
> 
> Month	Code
> January	A
> February	B
> March	C
> April	D
> May	E
> June	H
> July	L
> August	M
> September	P
> October	R
> November	S
> December	T
> Another thing:
> 
> > odd chars = UPV5J361 = 16+10+10+13+21+7+15+0 = 92
> 
> Why is `P = 10` here? Mistake or some special rule?
Sounds great. You're right, months are also invalid, thx for checking carefully. :) 
Sorry,  P = 10 is a mistake, should be 3.
