### ISSUE TITLE
Placeholder.com doesn't exist, so image() no longer works

### ISSUE THREAD

**Issue by jamiethorpe** [FakerPHP/Faker#645]
### Summary

Placeholder.com was bought by another company and the domain was moved today. This is resulting in gateway timeouts when using  the `image()` method.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1   |
| `fakerphp/faker`  | 1.21.0   |

### Self-enclosed code snippet for reproduction

```php
$faker = Faker\Factory::create();
$image = $faker->image('storage/app', 360, 360, 'animals', false, true, 'cats', false, 'jpg');
```

### Expected output

```txt
A 360x360 image
```

### Actual output

```txt
A gateway timeout
```

Every now and then you might receive an image, but it's likely just cached on a CDN that hasn't been updated.

**Comment by ErickZH** [comment]
Same problem. The new site is https://placehold.co/

**Comment by pimjansen** [comment]
See issue history
