### ISSUE TITLE
Version 1.22 not available on packagist

### ISSUE THREAD

**Issue by ghost** [FakerPHP/Faker#649]
Hello,

It looks like the latest release was not properly tagged. No version 1.22.0 appears on packagist after 2 days. The version 1.21.x-dev was updated instead.

![Screenshot_20230516-132613-300.png](https://github.com/FakerPHP/Faker/assets/36995639/f2592331-e8cf-4f9d-a303-01afb0179e89)

**Comment by bram-pkg** [comment]
I've updated the Packagist package now. Thanks!
