### ISSUE TITLE
Feature request name without special character

### ISSUE THREAD

**Issue by agus24** [FakerPHP/Faker#650]
### Summary

i did some test using laravel with faker. but sometimes it generates name like `Ambrose O'Conner` then i assert html has that name but the html generated like this `Ambrose O&#039;Conner` is there a way to remove special character in name? or other way to resolve this issue?

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1.18   |
| `fakerphp/faker`  | 1.21.0   |

### Self-enclosed code snippet for reproduction

```php
class OutletFactory extends Factory 
{
    public function definition()
    {
        return [
            'name' => fake()->name()
        ];
    }
}
```

```php
$outlet = Outlet::factory()->create();
Livewire::test(EventPage::class)->assertSeeHtml($outlet->name) // this fails
```

### Expected output

```txt
Ambrose O'Conner found on html
```

### Actual output

```txt
Ambrose O'Conner does not found on html. but `Ambrose O&#039;Conner` found
```

**Comment by bram-pkg** [comment]
You should escape the HTML when using `assertSeeHtml`, that would fix this. Unfortunately names like these are valid and your tests should probably keep them in mind ;)

**Comment by bram-pkg** [comment]
<img width="477" alt="Screenshot 2023-05-22 at 09 27 54" src="https://github.com/FakerPHP/Faker/assets/13304739/54f9f515-eaf4-4079-a752-3f33f5d311c8">

From what I see in the Livewire code, the `assertSee` has an option to automatically escape text :)
