### ISSUE TITLE
Wrong lv_LV postcode format

### ISSUE THREAD

**Issue by alexostrovskyferratum** [FakerPHP/Faker#652]
### Summary

Wrong lv_LV postcode format "LV ####" should be "LV-####"

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.2.6   |
| `fakerphp/faker`  | 1.22.0   |

https://en.wikipedia.org/wiki/Postal_codes_in_Latvia#:~:text=Postal%20codes%20in%20Latvia%20are,is%20%E2%80%9CLV%2DNNNN%E2%80%9D.

**Comment by pimjansen** [comment]
This article does not cite any sources. (June 2019

**Comment by alexostrovskyferratum** [comment]
@pimjansen I checked multiple sources from google and also we have this validation for years in LV market.

**Comment by pimjansen** [comment]
Ok, feel free to raise an PR in this case to update
