### ISSUE TITLE
dateTimeThisYear generating invalid datetimes

### ISSUE THREAD

**Issue by iBotPeaches** [FakerPHP/Faker#66]
### Summary

I'm not sure this is fixable, but I occasionally get test failures because the random dateTime it generates it like during an hour that doesn't exist in the year due to daylight savings.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.11  |
| `fakerphp/faker`  | v1.11.0   |

### Self-enclosed code snippet for reproduction

```php
User = User::query()->create([
    'google_id' => $this->faker->unique()->numerify('#####################'),
    'foo' => $this->faker->dateTimeThisYear,
]);

// Insert `foo` into db column `timestamp` on `users` table.
```

### Expected output

```txt
Insert to work
```

### Actual output

```txt
  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2020-03-08 02:24:45' for column `users`.`foo` at row 1 (SQL: insert into `users` (`google_id`, `foo`, `updated_at`, `created_at`) values (253337100756074437708, 2020-03-08 02:24:45, 2020-11-21 11:46:14, 2020-11-21 11:46:14))
```
* `2020-03-08 02:24:45` is between the 2-3am hour when daylight savings occur, so that hour effectively is removed.

I'm not even sure if this is Faker's responsibility or if this is mine with setting time zones, configuring database (MariaDB 10.2) or something else. I'd figured I throw a bug in first to be sure.

**Comment by IonBazan** [comment]
It is not faker issue as the date exists in the time zone you are using to generate the date (UTC I suppose). You can pass an optional argument for faker provider to generate the DateTime object in specified time zone matching your database to make sure it will be persisted. You may also want to verify your MariaDB and PHP default time zone settings as it will affect the rest of your app.

**Comment by pimjansen** [comment]
What i don't understand how a time can not exist? Everyday has 24 hours actually even during transition time. So  how can a date have an invalid time?

**Comment by pimjansen** [comment]
Agree that Faker should return a valid date though in this case. Marking this as a bug

**Comment by pimjansen** [comment]
I was wrong as it is as @IonBazan suggested. The instance will create a date on utc time which does not have daylight saving. There is a param for setting the timezone

**Comment by iBotPeaches** [comment]
What I'm lost on it is why the default doesn't appear to be working. Yes that timezone is invalid in my timezone (Eastern) and I can see that via 

```
➜  foo git:(master) php -i | grep 'timezone'
Default timezone => America/New_York
date.timezone => no value => no value
```

Though the [docs](https://github.com/fzaninotto/Faker#fakerproviderdatetime) say:

> Methods accepting a $timezone argument default to date_default_timezone_get(). You can pass a custom timezone string to each method, or define a custom timezone for all time methods at once using $faker::setDefaultTimezone($timezone).

So I don't use any parameters so it should default to `date_default_timezone_get()` no?

```
➜  foo git:(master) php artisan tinker
Psy Shell v0.10.4 (PHP 7.4.11 — cli) by Justin Hileman
>>> date_default_timezone_get()
=> "UTC"
>>> 
```

Even the Laravel config:
```
    /*
    |--------------------------------------------------------------------------
    | Application Timezone
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default timezone for your application, which
    | will be used by the PHP date and date-time functions. We have gone
    | ahead and set this to a sensible default for you out of the box.
    |
    */

    'timezone' => 'UTC',
```

This is where I got confused and just made a ticket. I'm not sure where the fault is.

**Comment by pimjansen** [comment]
No idea neither however Faker is returning a date as expected where your DB returns an error. The generated date is a valid utc date this year

**Comment by IonBazan** [comment]
@iBotPeaches Since you stay in America/New_York time zone, most probably your database time zone is set to America/New_York while your app is working in UTC. You should change the database default time zone to UTC too to avoid converting the date each time you want to persist or retrieve it from DB.
