### ISSUE TITLE
NZ Provider has no e.164 number format

### ISSUE THREAD

**Issue by securit** [FakerPHP/Faker#671]
### Summary

The src/Faker/Provider/en_NZ/PhoneNumber.php does not contain an e.164 format array or international format strings in the `protected static $formats` array.

```
protected static $e164Formats = [
        '+64##########',
    ];
```

### Versions

|                | Version |
|:---------------|:--------|
| `fakerphp/faker`  | 1.23.0   |

### Self-enclosed code snippet for reproduction
see `src/Faker/Provider/en_NZ/PhoneNumber.php`

### Expected output
```
protected static $formats = [
     // National format
    '0{{areaCode}}{{beginningNumber}}######',
    '0{{areaCode}} {{beginningNumber}}######',
    '0{{areaCode}} {{beginningNumber}}## ####',
     
    // Optional parenthesis
    '(0{{areaCode}}){{beginningNumber}}######',
    '(0{{areaCode}}){{beginningNumber}}## ####',
    '(0{{areaCode}}) {{beginningNumber}}######',
    '(0{{areaCode}}) {{beginningNumber}}## ####',

    // International format drops the 0
    '+64{{areaCode}}{{beginningNumber}}######',
    '+64 {{areaCode}} {{beginningNumber}}## ####',
    '+64 {{areaCode}} {{beginningNumber}}######',
    '+64 ({{areaCode}}) {{beginningNumber}}## ####',
    '+64 ({{areaCode}}) {{beginningNumber}}######',
    '+64({{areaCode}}){{beginningNumber}}## ####',
    '+64({{areaCode}}){{beginningNumber}}######',
    '+64({{areaCode}}) {{beginningNumber}}## ####',
    '+64({{areaCode}}) {{beginningNumber}}######',
];

/**
 * An array of en_NZ landline area codes
 *
 * @var array
 */
protected static $areaCodes = [
    '2', '3', '4', '6', '7', '9',
];

protected static $e164Formats = [
    '+64##########',
];
```

### Actual output
see `src/Faker/Provider/en_NZ/PhoneNumber.php`

**Comment by pimjansen** [comment]
Feel free to raise a PR with the valid format and link to some specific reference data to verify the format

**Comment by securit** [comment]
The New Zealand numbering plan is administered by The Ministry of Business and innovation via The Number Administration Deed (https://www.nad.org.nz <https://www.nad.org.nz/>)

The rules for number allocation are here https://www.nad.org.nz/assets/ResourceLinks/NAD-Rules-v7.1.pdf
 
The New Zealand numbering plan is found here https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000990002PDFE.pdf

**Comment by securit** [comment]
This repository does not permit the creation of new PRs because

This repository has been archived by the owner on Dec 12, 2020. It is now read-only.

**Comment by securit** [comment]
Hey stale bot. Dont shoot the messenger!

**Comment by localheinz** [comment]
@securit 

We may consider adding such a feature in the future, but the current plans for `2.0.0` indicate that providers for specific locales will be removed from `fakerphp/faker`.
