### ISSUE TITLE
Faker image generator returns 0

### ISSUE THREAD

**Issue by scarneros** [FakerPHP/Faker#68]
### Summary

Faker image generator doesn't store any image and return 0 (false) as a result.
Curl extension is enabled on php.ini and allow_url_fopen is set to On.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 7.4.7   |
| `fakerphp/faker`  | 1.9.1   |

### Self-enclosed code snippet for reproduction

```php
<?php

$faker = Faker\Factory::create();

echo $faker->image("public/storage/avatars", 400, 400, "people");
```

### Expected output

```txt
the path of the stored image file (i.e. public/storage/avatars/13b73edae8443990be1aa8f1a483bc27.jpg)
```

### Actual output

```txt
0
```

**Comment by pimjansen** [comment]
Can you confirm that the script is able to write to the given directory?

**Comment by scarneros** [comment]
Seems like it was an error with permissions on Windows as now it's correctly working on my macbook pro for version 1.9.1. Thanks.

**Comment by asolopovas** [comment]
I am having the same issue, I am on Arch Linux, tried giving 777 permissions to the folder it still returns 0

**Comment by asolopovas** [comment]
ok was my connection to via.placeholder.com fixed seems to work now
