### ISSUE TITLE
[QUESTION] Avoid "unwanted" results

### ISSUE THREAD

**Issue by SiestaCat** [FakerPHP/Faker#680]
Hello

`echo $faker->email();`

Just output `porn@yahoo.com`

How to avoid generating this "unwanted" result? Like `porn` or another similar keywords.

Thanks

**Comment by DvDty** [comment]
Try safeEmail

https://fakerphp.github.io/formatters/internet/

**Comment by pimjansen** [comment]
> Try safeEmail
> 
> https://fakerphp.github.io/formatters/internet/

SafeEmail wont resolve this since it will only remove all non string chars.

Which locale was this? As far as i can see in general only names are used to generate email addresses so

**Comment by DvDty** [comment]
Makes sense. You can also use the company name or first/last name in addition to domain generation to build yourself an email.
