### ISSUE TITLE
fzaninotto/Faker should suggest this package as replacement

### ISSUE THREAD

**Issue by c33s** [FakerPHP/Faker#69]
@fzaninotto can you please do that for us?

**Comment by chris-doehring** [comment]
We would indeed appreciate that, but as already mentioned [here](https://github.com/FakerPHP/Faker/issues/40), you should directly contact the author. It's not an issue primarily related to this fork.

**Comment by c33s** [comment]
@chris-doehring i contacted the author with the help of your issue board by using the @ natation. so maybe you keep the issue open and we hope @fzaninotto reads it here. i opened the issue here because the orginal repo is archived and so issues can't be created there

**Comment by bramceulemans** [comment]
I highly doubt it, since fzaninotto's repository is archived.

**Comment by pimjansen** [comment]
Also reached out via Twitter without reply
