### ISSUE TITLE
Austrian provider in de_AT as well as in at_AT

### ISSUE THREAD

**Issue by krsriq** [FakerPHP/Faker#71]
Is there a reason that Austria can be found in Providers/de_AT and in Providers/at_AT?

at_AT is rather empty except for a Payment.php file - in which obvious code duplication is happening:
https://github.com/FakerPHP/Faker/blob/9f1d7e8f501d9b1d4049e9e35345e576594baa31/src/Faker/Provider/at_AT/Payment.php#L35-L38
https://github.com/FakerPHP/Faker/blob/9f1d7e8f501d9b1d4049e9e35345e576594baa31/src/Faker/Provider/de_AT/Payment.php#L15-L18

As I understand it the first part of a locale is the language, the second part the country code - at isn't a language, but a country with de/German as the official language.

To fix this the method https://github.com/FakerPHP/Faker/blob/9f1d7e8f501d9b1d4049e9e35345e576594baa31/src/Faker/Provider/at_AT/Payment.php#L20 would have to be moved to de_AT/Payment.php and at_AT/Payment.php be deleted (which would obviously be a breaking change).

**Comment by bramceulemans** [comment]
We have already taken note in this change. `at_AT` will be removed in 2.0.

See: https://fakerphp.github.io/#misnamed-locales

**Comment by krsriq** [comment]
You mean like that? How about documenting this somewhere - e.g. directly in at_AT/Payment.php? Or is the long-term plan to remove at_AT entirely?

**Comment by bramceulemans** [comment]
Thanks for the PR, looks good to me.
