### ISSUE TITLE
Drop support for PHP 7.4

### ISSUE THREAD

**Issue by localheinz** [FakerPHP/Faker#747]
PHP 7.4 has reached its end of life on November 28, 2022.

We should consider dropping support for PHP 7.4 for `2.0.0`.

Also see #743 and discussions in #543 and #733.

**Comment by DvDty** [comment]
Why is this labeled `bug`? Seems more like an `enhancement` to me.

**Comment by pimjansen** [comment]
> Why is this labeled `bug`? Seems more like an `enhancement` to me.

Well its just a label :)

**Comment by bram-pkg** [comment]
Should probably be enhancement
