### ISSUE TITLE
Stricter postcodes for AT?

### ISSUE THREAD

**Issue by krsriq** [FakerPHP/Faker#77]
In de_AT/Address.php there's a TODO comment to implement more strict postal code values:
https://github.com/FakerPHP/Faker/blob/6027e189112a79e37fdff41c1f7f77df0dc90ab5/src/Faker/Provider/de_AT/Address.php#L16-L17

I looked through the other address providers - some have a list of (presumably) all available postcodes (such as [en_GB](https://github.com/FakerPHP/Faker/blob/main/src/Faker/Provider/en_GB/Address.php)), some use numerify/regex to generate postcodes (such as [en_AU](https://github.com/FakerPHP/Faker/blob/main/src/Faker/Provider/en_AU/Address.php)), others use completely random numbers.

Does it make sense to have a list of all valid postal codes hard coded, as the comment suggests? Especially since a generated address would then still be likely invalid, because it's a random combination of a postal code and a city
https://github.com/FakerPHP/Faker/blob/d55d5aacf05163fb99103f2de018daf4ebbb1fd9/src/Faker/Provider/de_AT/Address.php#L97

So one possible solution would be to just remove that TODO comment and live with invalid postal codes, or to hard code all available postal codes (and still live with invalid postal code/city combinations).
A more advanced solution would be to build a data structure that has a hierarchy of state-postcode-city, so only valid combinations are possible - but that would probably be overkill (and a solution I couldn't find in any other providers)?

**Comment by pimjansen** [comment]
Imo a faker method should return valid data. If it is invalid it is useless to start with.

So if that means a lot of logic, then this is the case we have to deal with

**Comment by krsriq** [comment]
So this would then mean that you'd prefer a solution where
1.  `postcode()` returns a valid postcode
2.  `address()` returns a valid postcode-city combination? 

To be 100% valid `address()` would of course also have to be a valid __street__-postcode-city combination, meaning a pretty extensive list of valid streets per city..

**Comment by pimjansen** [comment]
> So this would then mean that you'd prefer a solution where
> 1.  `postcode()` returns a valid postcode
> 2.  `address()` returns a valid postcode-city combination? 
> 
> To be 100% valid `address()` would of course also have to be a valid __street__-postcode-city combination, meaning a pretty extensive list of valid streets per city..

Well we create fake data. This means that dummy names can be used there. However if we can build something that is more realistic it would always be good.

The most important thing imo is the format though

**Comment by krsriq** [comment]
Alright, then I'll implement a change where

1. `postcode()` returns a random existing postcode
2. `address()` returns a valid postcode-city combination while keeping the format ` "{{streetAddress}}\n{{postcode}} {{city}}"`, so `streetAdress` will remain fake.

Cool?

**Comment by pimjansen** [comment]
> Alright, then I'll implement a change where
> 
> 1. `postcode()` returns a random existing postcode
> 2. `address()` returns a valid postcode-city combination while keeping the format ` "{{streetAddress}}\n{{postcode}} {{city}}"`, so `streetAdress` will remain fake.
> 
> Cool?

Sounds good though its hard for me to decide where i have no clue how postalcodes in austria work.

But if you generate a valid postalcode city combination, the postalcode can also be valid from the same list right?

**Comment by krsriq** [comment]
Okay, than I'll just take the easier path and replace the existing randomly generated postcode with valid ones.
