### ISSUE TITLE
Warning DEPRECATED  use of static pt_BR PhoneNumber

### ISSUE THREAD

**Issue by medeiroz** [FakerPHP/Faker#784]
![image](https://github.com/FakerPHP/Faker/assets/11270546/c40e8aff-5160-4739-bf57-0f0a4ebe5125)

DEPRECATED  Use of "static" in callables is deprecated in vendor/fakerphp/faker/src/Faker/Provider/pt_BR/PhoneNumber.php on line 138.

**Comment by localheinz** [comment]
Related to #479.
