### ISSUE TITLE
Faker images links are broken

### ISSUE THREAD

**Issue by Carnicero90** [FakerPHP/Faker#797]
### Summary
_placeholder.com_ is no more: I guess they didn't renew their certs, so that now every fake image link doesn't work anymore.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.2.6   |
| `fakerphp/faker`  | 1.23.0   |

**Comment by pimjansen** [comment]
It is deprecated see older issues. We are not patching this

**Comment by Carnicero90** [comment]
I see, my apologies. Still in the docs, though? I guess I could send a pr to remove it.

**Comment by artifex-media** [comment]
Why won't this be patched? There are many alternatives to placeholder.com, such as https://picsum.photos/ - same concept.

**Comment by pimjansen** [comment]
> Why won't this be patched? There are many alternatives to placeholder.com, such as https://picsum.photos/ - same concept.

Because it is deprecated

**Comment by neoacevedo** [comment]
@pimjansen at least you should set in the documentation about the deprecation on that method because it looks like can be used:
https://fakerphp.github.io/formatters/image/#imageurl

**Comment by bram-pkg** [comment]
https://github.com/FakerPHP/fakerphp.github.io/pull/98 to document this
