### ISSUE TITLE
Unable to get any other text but Latin

### ISSUE THREAD

**Issue by hitriyvalenok** [FakerPHP/Faker#801]
### Summary

Faker ignores providers, continuing to generate Latin text

### Versions

1.23.0

### Self-enclosed code snippet for reproduction

```php
$faker = Factory::create( 'en_US' );
$faker->addProvider( new Faker\Provider\en_US\Text( $faker ) );
echo $faker->text;
```

### Expected output

```txt
Alice was beginning to get very tired of sitting by her sister on the bank.
```

### Actual output

```txt
Vero aut nobis soluta vitae. Amet quo enim inventore tempore.
```

**Comment by pimjansen** [comment]
What are your trying to do? See the code examples in the docs. There is no need to add the provider at all?

**Comment by hitriyvalenok** [comment]
I'm sorry, but your answer absolutely senseless. It's pretty obvious that I'm trying to generate text other than Latin. I've been using Faker for a few months and already have read the docs. Please, show me a sample where Faker generates English words.

**Comment by bram-pkg** [comment]
For actual English text `realText()` is used. It is also not recommended to use property access, but rather call the methods with the same name.

**Comment by hitriyvalenok** [comment]
Thanks! Is there a way also to get an English word?
