### ISSUE TITLE
E-commerce Plugin - Feature

### ISSUE THREAD

**Issue by muratcakmaksoftware** [FakerPHP/Faker#823]
e-commerce is a widely used platform. Probably others may have needed it like me. 
I need fake product names or brand names or anything related to e-commerce but I couldn't find what I wanted, maybe you can work on that in a plugin style.

**Comment by DannyvdSluijs** [comment]
@muratcakmaksoftware I believe this is actually already possible. Using the Provider system you can easily create your own extensions. See https://github.com/jzonta/FakerRestaurant/blob/master/src/Provider/en_US/Restaurant.php for example which adds restaurant support. 

I guess if you open source it you can even create PR on the [fakerphp.github.io](https://github.com/FakerPHP/fakerphp.github.io) repo and get you provider listen on https://fakerphp.github.io/third-party/
