### ISSUE TITLE
Feature Request: Adjective Animal

### ISSUE THREAD

**Issue by gam6itko** [FakerPHP/Faker#834]
### Summary

It will be very useful to have a feature to generate random animal names, such as a Google sheet or Ubuntu releases.

Like:
- Lunar Lobster
- Сurious Fox

I found such a library, but it does not support i18n.
- https://github.com/nubs/random-name-generator

**Comment by pimjansen** [comment]
Create a custom provider. Faker can not create everything that has an usecase

**Comment by gam6itko** [comment]
I got it. I create [repo](https://github.com/gam6itko/fakerphp-animal-provider) for this feature. May be it will be useful for someone
