### ISSUE TITLE
Is it maintained ?

### ISSUE THREAD

**Issue by jdecool** [FakerPHP/Faker#887]
It seems that the project has a slow activity.

There's no commit on main branches, there's no issue closed recently and no pull request has recently been merged.

I want to know if this project is actively maintained ?

Do you need help for some issues ? or features ?

Thanks.

This library is awesome, I don't want to see it dead.

**Comment by GrahamCampbell** [comment]
Yes, it's still maintained, and very much the current version works great.

**Comment by GrahamCampbell** [comment]
If you'd like to work on some issues by preparing PRs, or help with reviewing existing PRs, it would be much appreciated. I am aware that it has been a while since a commit was last pushed to one of the main branches - you are not wrong. ;)

**Comment by kcassam** [comment]
Maybe let's begin with the 27 PRs in stock

**Comment by jdecool** [comment]
Thanks for your answer @GrahamCampbell 

I first want to work on a problem we face using Faker and that impacts other libraries like Alice, Foundry and others.

It's related to the seed management and there's an [existing issue](https://github.com/FakerPHP/Faker/issues/870) about it. I've also noticed that there's already a merge request to try to solve this problem (https://github.com/FakerPHP/Faker/pull/871).

The merge request is currently mark as `stale`. Do you think it is possible to have a look ?

**Comment by jdecool** [comment]
>  the current version works great

I agree there's no big problem with Faker.

But I also think that we can make some improvements.

**Comment by GlennM** [comment]
What about this one, latest activity from about half a year ago. Are there any updates?

https://github.com/FakerPHP/Faker/discussions/15

**Comment by pimjansen** [comment]
> What about this one, latest activity from about half a year ago. Are there any updates?
> 
> 
> 
> https://github.com/FakerPHP/Faker/discussions/15

Not much, except the fact that we are also busy with our day to day jobs. 

But since i have seen you post a few times earlier, feel free to contribute!
