### ISSUE TITLE
Dependency on doctrine/persistence on v1.23 prevents from upgrading fully to symfony 6.4

### ISSUE THREAD

**Issue by oaygalenq** [FakerPHP/Faker#899]
Hi,

The dependency to doctrine/persistence v1 or v2 prevents from upgrading symfony/doctrine-bridge to v6.4 because it has a dependency on doctrine/persistence v3. Could you please add support of doctrine/persistence v3?

Regards

**Comment by Jubeki** [comment]
Are you sure this is related to the fackerphp/faker package?

Because this is not a composer dependency:
https://github.com/FakerPHP/Faker/blob/4dae775c9fbd5d734f5307b73e29d34adf289e50/composer.json#L16-L20

**Comment by DvDty** [comment]
> Are you sure this is related to the fackerphp/faker package?
> 
> Because this is not a composer dependency:
> 
> https://github.com/FakerPHP/Faker/blob/4dae775c9fbd5d734f5307b73e29d34adf289e50/composer.json#L16-L20

It's listed as dev dependency:

https://github.com/FakerPHP/Faker/blob/4dae775c9fbd5d734f5307b73e29d34adf289e50/composer.json#L21-L24

@oaygalenq how are you installing Faker?

**Comment by Jubeki** [comment]
Dev dependencies are not installed on the project where Faker is being used, so it should not be a problem for this case.

This should be updated for the tests and so one, but should have no influence on installing faker as a composer dependency.
