### ISSUE TITLE
Invalid E.164 format for pt_PT PhoneNumber Provider

### ISSUE THREAD

**Issue by Head0nF1re** [FakerPHP/Faker#925]
### Summary

According to PHPDoc/DockBlock, the `Generator` class should have the method `e164PhoneNumber`. However, calling `fake('pt_PT')->unique()->e164PhoneNumber()` (`fake` is a Laravel abstraction over `Faker\Factory::create`) returns numbers for multiple locales.

This happens because the `pt_PT` provider (`Faker\Provider\pt_PT\PhoneNumber`) doesn't override the property `e164Formats` from the base class in order to provide locale specific E.164 phone formats.

I will create a PR to fix the issue.
### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.3   |
| `fakerphp/faker`  | 1.23   |

**Comment by pimjansen** [comment]
This is as intended since the method is not implemented for the locale itself

**Comment by Head0nF1re** [comment]
> This is as intended since the method is not implemented for the locale itself

@pimjansen What do you mean, did you have a look at the PR #926? It doesn't make much sense to have a factory to create locale specific generators that register providers that don't provide locale specific data, IMO.

If we look at similar issues:
- https://github.com/FakerPHP/Faker/issues/358
- https://github.com/FakerPHP/Faker/issues/332

We can see that they report the same thing. Also, if we look at each provider PhoneNumber class (`uk_UA` and `en_US`), the property `$e164Formats` is overridden in order to provide locale specific phone numbers. 
The global ones can still be provided when using the base PhoneNumber class...
